package com.shopoperate.common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("article_categories", "id", ArticleCategories.class);
		arp.addMapping("articles", "id", Articles.class);
		arp.addMapping("attendance_records", "id", AttendanceRecords.class);
		arp.addMapping("commission_rules", "id", CommissionRules.class);
		arp.addMapping("commission_settlements", "id", CommissionSettlements.class);
		arp.addMapping("coupon_usages", "id", CouponUsages.class);
		arp.addMapping("coupon_verification_logs", "id", CouponVerificationLogs.class);
		arp.addMapping("coupons", "id", Coupons.class);
		arp.addMapping("customer_sessions", "id", CustomerSessions.class);
		arp.addMapping("customer_wallets", "id", CustomerWallets.class);
		arp.addMapping("customers", "id", Customers.class);
		arp.addMapping("daily_snapshots", "id", DailySnapshots.class);
		arp.addMapping("expense_categories", "id", ExpenseCategories.class);
		arp.addMapping("expenses", "id", Expenses.class);
		arp.addMapping("feedbacks", "id", Feedbacks.class);
		arp.addMapping("game_sessions", "id", GameSessions.class);
		arp.addMapping("inventory", "id", Inventory.class);
		arp.addMapping("inventory_transactions", "id", InventoryTransactions.class);
		arp.addMapping("invoices", "id", Invoices.class);
		arp.addMapping("materials", "id", Materials.class);
		arp.addMapping("notification_logs", "id", NotificationLogs.class);
		arp.addMapping("operation_logs", "id", OperationLogs.class);
		arp.addMapping("package_bom", "id", PackageBom.class);
		arp.addMapping("packages", "id", Packages.class);
		arp.addMapping("permissions", "id", Permissions.class);
		arp.addMapping("points_records", "id", PointsRecords.class);
		arp.addMapping("prepayments", "id", Prepayments.class);
		arp.addMapping("purchase_order_items", "id", PurchaseOrderItems.class);
		arp.addMapping("purchase_orders", "id", PurchaseOrders.class);
		arp.addMapping("purchase_payments", "id", PurchasePayments.class);
		arp.addMapping("purchases", "id", Purchases.class);
		arp.addMapping("queue_entries", "id", QueueEntries.class);
		arp.addMapping("refund_records", "id", RefundRecords.class);
		arp.addMapping("revenue_records", "id", RevenueRecords.class);
		// Composite Primary Key order: role_id,permission_id
		arp.addMapping("role_permissions", "role_id,permission_id", RolePermissions.class);
		arp.addMapping("roles", "id", Roles.class);
		arp.addMapping("seat_subscriptions", "id", SeatSubscriptions.class);
		arp.addMapping("seat_subscriptions_transactions", "id", SeatSubscriptionsTransactions.class);
		arp.addMapping("shop_faqs", "id", ShopFaqs.class);
		arp.addMapping("shops", "id", Shops.class);
		arp.addMapping("staff", "id", Staff.class);
		arp.addMapping("staff_accounts", "id", StaffAccounts.class);
		// Composite Primary Key order: staff_id,role_id
		arp.addMapping("staff_roles", "staff_id,role_id", StaffRoles.class);
		arp.addMapping("staff_schedules", "id", StaffSchedules.class);
		arp.addMapping("staff_shops", "id", StaffShops.class);
		arp.addMapping("suppliers", "id", Suppliers.class);
		arp.addMapping("sys_dicts", "id", SysDicts.class);
		arp.addMapping("wallet_transactions", "id", WalletTransactions.class);
	}
}


