package com.shopoperate.common.model;

import com.shopoperate.common.model.base.BaseArticles;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Articles extends BaseArticles<Articles> {
	
}

