package com.shopoperate.common.model;

import com.shopoperate.common.model.base.BaseArticleCategories;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ArticleCategories extends BaseArticleCategories<ArticleCategories> {
	
}

