package com.shopoperate.common.model;

import com.shopoperate.common.model.base.BaseAttendanceRecords;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AttendanceRecords extends BaseAttendanceRecords<AttendanceRecords> {
	
}

