package com.shopoperate.common.model;

import com.shopoperate.common.model.base.BaseCommissionRules;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CommissionRules extends BaseCommissionRules<CommissionRules> {
	
}

