package com.shopoperate.common.model;

import com.shopoperate.common.model.base.BaseCommissionSettlements;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CommissionSettlements extends BaseCommissionSettlements<CommissionSettlements> {
	
}

