package com.shopoperate.common.model;

import com.shopoperate.common.model.base.BaseCouponVerificationLogs;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CouponVerificationLogs extends BaseCouponVerificationLogs<CouponVerificationLogs> {
	
}

