package com.shopoperate.common.model;

import com.shopoperate.common.model.base.BaseCouponUsages;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CouponUsages extends BaseCouponUsages<CouponUsages> {
	
}

