package com.shopoperate.common.model;

import com.shopoperate.common.model.base.BaseCoupons;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Coupons extends BaseCoupons<Coupons> {
	
}

