package com.shopoperate.common.model;

import com.shopoperate.common.model.base.BaseCustomers;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Customers extends BaseCustomers<Customers> {
	
}

