package com.shopoperate.common.model;

import com.shopoperate.common.model.base.BaseCustomerSessions;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CustomerSessions extends BaseCustomerSessions<CustomerSessions> {
	
}

