package com.shopoperate.common.model;

import com.shopoperate.common.model.base.BaseDailySnapshots;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DailySnapshots extends BaseDailySnapshots<DailySnapshots> {
	
}

