package com.shopoperate.common.model;

import com.shopoperate.common.model.base.BaseExpenses;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Expenses extends BaseExpenses<Expenses> {
	
}

