package com.shopoperate.common.model;

import com.shopoperate.common.model.base.BaseExpenseCategories;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ExpenseCategories extends BaseExpenseCategories<ExpenseCategories> {
	
}

