package com.shopoperate.common.model;

import com.shopoperate.common.model.base.BaseFeedbacks;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Feedbacks extends BaseFeedbacks<Feedbacks> {
	
}

