package com.shopoperate.common.model;

import com.shopoperate.common.model.base.BaseGameSessions;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GameSessions extends BaseGameSessions<GameSessions> {
	
}

