package com.shopoperate.common.model;

import com.shopoperate.common.model.base.BaseInventoryTransactions;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class InventoryTransactions extends BaseInventoryTransactions<InventoryTransactions> {
	
}

