package com.shopoperate.common.model;

import com.shopoperate.common.model.base.BaseInventory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Inventory extends BaseInventory<Inventory> {
	
}

