package com.shopoperate.common.model;

import com.shopoperate.common.model.base.BaseInvoices;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Invoices extends BaseInvoices<Invoices> {
	
}

