package com.shopoperate.common.model;

import com.shopoperate.common.model.base.BaseNotificationLogs;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class NotificationLogs extends BaseNotificationLogs<NotificationLogs> {
	
}

