package com.shopoperate.common.model;

import com.shopoperate.common.model.base.BaseOperationLogs;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OperationLogs extends BaseOperationLogs<OperationLogs> {
	
}

