package com.shopoperate.common.model;

import com.shopoperate.common.model.base.BasePackages;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Packages extends BasePackages<Packages> {
	
}

