package com.shopoperate.common.model;

import com.shopoperate.common.model.base.BasePackageBom;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PackageBom extends BasePackageBom<PackageBom> {
	
}

