package com.shopoperate.common.model;

import com.shopoperate.common.model.base.BasePermissions;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Permissions extends BasePermissions<Permissions> {
	
}

