package com.shopoperate.common.model;

import com.shopoperate.common.model.base.BasePointsRecords;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PointsRecords extends BasePointsRecords<PointsRecords> {
	
}

