package com.shopoperate.common.model;

import com.shopoperate.common.model.base.BasePrepayments;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Prepayments extends BasePrepayments<Prepayments> {
	
}

