package com.shopoperate.common.model;

import com.shopoperate.common.model.base.BasePurchasePayments;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PurchasePayments extends BasePurchasePayments<PurchasePayments> {
	
}

