package com.shopoperate.common.model;

import com.shopoperate.common.model.base.BasePurchaseOrders;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PurchaseOrders extends BasePurchaseOrders<PurchaseOrders> {
	
}

