package com.shopoperate.common.model;

import com.shopoperate.common.model.base.BasePurchaseOrderItems;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PurchaseOrderItems extends BasePurchaseOrderItems<PurchaseOrderItems> {
	
}

