package com.shopoperate.common.model;

import com.shopoperate.common.model.base.BasePurchases;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Purchases extends BasePurchases<Purchases> {
	
}

