package com.shopoperate.common.model;

import com.shopoperate.common.model.base.BaseQueueEntries;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class QueueEntries extends BaseQueueEntries<QueueEntries> {
	
}

