package com.shopoperate.common.model;

import com.shopoperate.common.model.base.BaseRefundRecords;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RefundRecords extends BaseRefundRecords<RefundRecords> {
	
}

