package com.shopoperate.common.model;

import com.shopoperate.common.model.base.BaseRevenueRecords;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RevenueRecords extends BaseRevenueRecords<RevenueRecords> {
	
}

