package com.shopoperate.common.model;

import com.shopoperate.common.model.base.BaseRoles;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Roles extends BaseRoles<Roles> {
	
}

