package com.shopoperate.common.model;

import com.shopoperate.common.model.base.BaseRolePermissions;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RolePermissions extends BaseRolePermissions<RolePermissions> {
	
}

