package com.shopoperate.common.model;

import com.shopoperate.common.model.base.BaseSeatSubscriptions;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SeatSubscriptions extends BaseSeatSubscriptions<SeatSubscriptions> {
	
}

