package com.shopoperate.common.model;

import com.shopoperate.common.model.base.BaseSeatSubscriptionsTransactions;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SeatSubscriptionsTransactions extends BaseSeatSubscriptionsTransactions<SeatSubscriptionsTransactions> {
	
}

