package com.shopoperate.common.model;

import com.shopoperate.common.model.base.BaseShopFaqs;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ShopFaqs extends BaseShopFaqs<ShopFaqs> {
	
}

