package com.shopoperate.common.model;

import com.shopoperate.common.model.base.BaseShops;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Shops extends BaseShops<Shops> {
	
}

