package com.shopoperate.common.model;

import com.shopoperate.common.model.base.BaseStaffSchedules;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StaffSchedules extends BaseStaffSchedules<StaffSchedules> {
	
}

