package com.shopoperate.common.model;

import com.shopoperate.common.model.base.BaseStaffShops;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StaffShops extends BaseStaffShops<StaffShops> {
	
}

