package com.shopoperate.common.model;

import com.shopoperate.common.model.base.BaseStaffRoles;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StaffRoles extends BaseStaffRoles<StaffRoles> {
	
}

