package com.shopoperate.common.model;

import com.shopoperate.common.model.base.BaseStaff;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Staff extends BaseStaff<Staff> {
	
}

