package com.shopoperate.common.model;

import com.shopoperate.common.model.base.BaseStaffAccounts;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StaffAccounts extends BaseStaffAccounts<StaffAccounts> {
	
}

