package com.shopoperate.common.model;

import com.shopoperate.common.model.base.BaseSuppliers;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Suppliers extends BaseSuppliers<Suppliers> {
	
}

