package com.shopoperate.common.model;

import com.shopoperate.common.model.base.BaseSysDicts;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysDicts extends BaseSysDicts<SysDicts> {
	
}

