package com.shopoperate.common.model;

import com.shopoperate.common.model.base.BaseWalletTransactions;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WalletTransactions extends BaseWalletTransactions<WalletTransactions> {
	
}

