package com.shopoperate.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCommissionRules<M extends BaseCommissionRules<M>> extends Model<M> implements IBean {

	public void setId(java.math.BigInteger id) {
		set("id", id);
	}
	
	public java.math.BigInteger getId() {
		return getBigInteger("id");
	}
	
	public void setShopId(java.math.BigInteger shopId) {
		set("shop_id", shopId);
	}
	
	public java.math.BigInteger getShopId() {
		return getBigInteger("shop_id");
	}
	
	public void setRoleId(java.math.BigInteger roleId) {
		set("role_id", roleId);
	}
	
	public java.math.BigInteger getRoleId() {
		return getBigInteger("role_id");
	}
	
	/**
	 * 规则类型: 1-按次, 2-按流水比例, 3-固定金额
	 */
	public void setRuleType(java.lang.Integer ruleType) {
		set("rule_type", ruleType);
	}
	
	/**
	 * 规则类型: 1-按次, 2-按流水比例, 3-固定金额
	 */
	public java.lang.Integer getRuleType() {
		return getInt("rule_type");
	}
	
	public void setValue(java.math.BigDecimal value) {
		set("value", value);
	}
	
	public java.math.BigDecimal getValue() {
		return getBigDecimal("value");
	}
	
	public void setDescription(java.lang.String description) {
		set("description", description);
	}
	
	public java.lang.String getDescription() {
		return getStr("description");
	}
	
	public void setIsActive(java.lang.Integer isActive) {
		set("is_active", isActive);
	}
	
	public java.lang.Integer getIsActive() {
		return getInt("is_active");
	}
	
	public void setCreatedAt(java.util.Date createdAt) {
		set("created_at", createdAt);
	}
	
	public java.util.Date getCreatedAt() {
		return getDate("created_at");
	}
	
	/**
	 * 0-正常，1-已删除
	 */
	public void setIsDeleted(java.lang.Integer isDeleted) {
		set("is_deleted", isDeleted);
	}
	
	/**
	 * 0-正常，1-已删除
	 */
	public java.lang.Integer getIsDeleted() {
		return getInt("is_deleted");
	}
	
	/**
	 * 删除时间
	 */
	public void setDeletedTime(java.util.Date deletedTime) {
		set("deleted_time", deletedTime);
	}
	
	/**
	 * 删除时间
	 */
	public java.util.Date getDeletedTime() {
		return getDate("deleted_time");
	}
	
}

