package com.shopoperate.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCommissionSettlements<M extends BaseCommissionSettlements<M>> extends Model<M> implements IBean {

	public void setId(java.math.BigInteger id) {
		set("id", id);
	}
	
	public java.math.BigInteger getId() {
		return getBigInteger("id");
	}
	
	public void setShopId(java.math.BigInteger shopId) {
		set("shop_id", shopId);
	}
	
	public java.math.BigInteger getShopId() {
		return getBigInteger("shop_id");
	}
	
	public void setStaffId(java.math.BigInteger staffId) {
		set("staff_id", staffId);
	}
	
	public java.math.BigInteger getStaffId() {
		return getBigInteger("staff_id");
	}
	
	public void setSettlementPeriod(java.lang.String settlementPeriod) {
		set("settlement_period", settlementPeriod);
	}
	
	public java.lang.String getSettlementPeriod() {
		return getStr("settlement_period");
	}
	
	public void setTotalSessions(java.lang.Long totalSessions) {
		set("total_sessions", totalSessions);
	}
	
	public java.lang.Long getTotalSessions() {
		return getLong("total_sessions");
	}
	
	public void setTotalRevenue(java.math.BigDecimal totalRevenue) {
		set("total_revenue", totalRevenue);
	}
	
	public java.math.BigDecimal getTotalRevenue() {
		return getBigDecimal("total_revenue");
	}
	
	public void setCommissionAmount(java.math.BigDecimal commissionAmount) {
		set("commission_amount", commissionAmount);
	}
	
	public java.math.BigDecimal getCommissionAmount() {
		return getBigDecimal("commission_amount");
	}
	
	/**
	 * 状态: 1-待结算, 2-已发放
	 */
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	/**
	 * 状态: 1-待结算, 2-已发放
	 */
	public java.lang.Integer getStatus() {
		return getInt("status");
	}
	
	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}
	
	/**
	 * 结算时使用的提成规则快照
	 */
	public void setRuleSnapshot(java.lang.String ruleSnapshot) {
		set("rule_snapshot", ruleSnapshot);
	}
	
	/**
	 * 结算时使用的提成规则快照
	 */
	public java.lang.String getRuleSnapshot() {
		return getStr("rule_snapshot");
	}
	
	public void setCreatedAt(java.util.Date createdAt) {
		set("created_at", createdAt);
	}
	
	public java.util.Date getCreatedAt() {
		return getDate("created_at");
	}
	
	/**
	 * 0-正常，1-已删除
	 */
	public void setIsDeleted(java.lang.Integer isDeleted) {
		set("is_deleted", isDeleted);
	}
	
	/**
	 * 0-正常，1-已删除
	 */
	public java.lang.Integer getIsDeleted() {
		return getInt("is_deleted");
	}
	
	/**
	 * 删除时间
	 */
	public void setDeletedTime(java.util.Date deletedTime) {
		set("deleted_time", deletedTime);
	}
	
	/**
	 * 删除时间
	 */
	public java.util.Date getDeletedTime() {
		return getDate("deleted_time");
	}
	
	/**
	 * 关联支出记录ID
	 */
	public void setExpenseId(java.lang.Long expenseId) {
		set("expense_id", expenseId);
	}
	
	/**
	 * 关联支出记录ID
	 */
	public java.lang.Long getExpenseId() {
		return getLong("expense_id");
	}
	
}

