package com.shopoperate.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCustomerSessions<M extends BaseCustomerSessions<M>> extends Model<M> implements IBean {

	public void setId(java.math.BigInteger id) {
		set("id", id);
	}
	
	public java.math.BigInteger getId() {
		return getBigInteger("id");
	}
	
	public void setShopId(java.math.BigInteger shopId) {
		set("shop_id", shopId);
	}
	
	public java.math.BigInteger getShopId() {
		return getBigInteger("shop_id");
	}
	
	public void setCustomerId(java.math.BigInteger customerId) {
		set("customer_id", customerId);
	}
	
	public java.math.BigInteger getCustomerId() {
		return getBigInteger("customer_id");
	}
	
	public void setPurchaseId(java.math.BigInteger purchaseId) {
		set("purchase_id", purchaseId);
	}
	
	public java.math.BigInteger getPurchaseId() {
		return getBigInteger("purchase_id");
	}
	
	public void setSessionDate(java.util.Date sessionDate) {
		set("session_date", sessionDate);
	}
	
	public java.util.Date getSessionDate() {
		return getDate("session_date");
	}
	
	/**
	 * 状态: 1-可用, 2-已核销, 3-已过期, 4-已退款
	 */
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	/**
	 * 状态: 1-可用, 2-已核销, 3-已过期, 4-已退款
	 */
	public java.lang.Integer getStatus() {
		return getInt("status");
	}
	
	public void setUsedAt(java.util.Date usedAt) {
		set("used_at", usedAt);
	}
	
	public java.util.Date getUsedAt() {
		return getDate("used_at");
	}
	
	public void setGameSessionId(java.math.BigInteger gameSessionId) {
		set("game_session_id", gameSessionId);
	}
	
	public java.math.BigInteger getGameSessionId() {
		return getBigInteger("game_session_id");
	}
	
	public void setCreatedAt(java.util.Date createdAt) {
		set("created_at", createdAt);
	}
	
	public java.util.Date getCreatedAt() {
		return getDate("created_at");
	}
	
	/**
	 * 0-正常，1-已删除
	 */
	public void setIsDeleted(java.lang.Integer isDeleted) {
		set("is_deleted", isDeleted);
	}
	
	/**
	 * 0-正常，1-已删除
	 */
	public java.lang.Integer getIsDeleted() {
		return getInt("is_deleted");
	}
	
	/**
	 * 删除时间
	 */
	public void setDeletedTime(java.util.Date deletedTime) {
		set("deleted_time", deletedTime);
	}
	
	/**
	 * 删除时间
	 */
	public java.util.Date getDeletedTime() {
		return getDate("deleted_time");
	}
	
}

