package com.shopoperate.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePurchases<M extends BasePurchases<M>> extends Model<M> implements IBean {

	public void setId(java.math.BigInteger id) {
		set("id", id);
	}
	
	public java.math.BigInteger getId() {
		return getBigInteger("id");
	}
	
	public void setShopId(java.math.BigInteger shopId) {
		set("shop_id", shopId);
	}
	
	public java.math.BigInteger getShopId() {
		return getBigInteger("shop_id");
	}
	
	public void setCustomerId(java.math.BigInteger customerId) {
		set("customer_id", customerId);
	}
	
	public java.math.BigInteger getCustomerId() {
		return getBigInteger("customer_id");
	}
	
	public void setPackageId(java.math.BigInteger packageId) {
		set("package_id", packageId);
	}
	
	public java.math.BigInteger getPackageId() {
		return getBigInteger("package_id");
	}
	
	/**
	 * purchase-购买套餐, recharge-充值
	 */
	public void setPurchaseType(java.lang.String purchaseType) {
		set("purchase_type", purchaseType);
	}
	
	/**
	 * purchase-购买套餐, recharge-充值
	 */
	public java.lang.String getPurchaseType() {
		return getStr("purchase_type");
	}
	
	/**
	 * 渠道标识: store/meituan/douyin/other
	 */
	public void setChannel(java.lang.String channel) {
		set("channel", channel);
	}
	
	/**
	 * 渠道标识: store/meituan/douyin/other
	 */
	public java.lang.String getChannel() {
		return getStr("channel");
	}
	
	public void setThirdPartyCouponCode(java.lang.String thirdPartyCouponCode) {
		set("third_party_coupon_code", thirdPartyCouponCode);
	}
	
	public java.lang.String getThirdPartyCouponCode() {
		return getStr("third_party_coupon_code");
	}
	
	/**
	 * 使用的优惠券记录ID
	 */
	public void setCouponUsageId(java.math.BigInteger couponUsageId) {
		set("coupon_usage_id", couponUsageId);
	}
	
	/**
	 * 使用的优惠券记录ID
	 */
	public java.math.BigInteger getCouponUsageId() {
		return getBigInteger("coupon_usage_id");
	}
	
	public void setStartDate(java.util.Date startDate) {
		set("start_date", startDate);
	}
	
	public java.util.Date getStartDate() {
		return getDate("start_date");
	}
	
	public void setTotalAmount(java.math.BigDecimal totalAmount) {
		set("total_amount", totalAmount);
	}
	
	public java.math.BigDecimal getTotalAmount() {
		return getBigDecimal("total_amount");
	}
	
	public void setPaidAmount(java.math.BigDecimal paidAmount) {
		set("paid_amount", paidAmount);
	}
	
	public java.math.BigDecimal getPaidAmount() {
		return getBigDecimal("paid_amount");
	}
	
	/**
	 * 优惠券抵扣金额
	 */
	public void setCouponDiscount(java.math.BigDecimal couponDiscount) {
		set("coupon_discount", couponDiscount);
	}
	
	/**
	 * 优惠券抵扣金额
	 */
	public java.math.BigDecimal getCouponDiscount() {
		return getBigDecimal("coupon_discount");
	}
	
	public void setPaymentMethod(java.lang.String paymentMethod) {
		set("payment_method", paymentMethod);
	}
	
	public java.lang.String getPaymentMethod() {
		return getStr("payment_method");
	}
	
	/**
	 * 状态: 1-有效, 2-已退款, 3-已过期
	 */
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	/**
	 * 状态: 1-有效, 2-已退款, 3-已过期
	 */
	public java.lang.Integer getStatus() {
		return getInt("status");
	}
	
	public void setOperatorStaffId(java.math.BigInteger operatorStaffId) {
		set("operator_staff_id", operatorStaffId);
	}
	
	public java.math.BigInteger getOperatorStaffId() {
		return getBigInteger("operator_staff_id");
	}
	
	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}
	
	public void setIsDeleted(java.lang.Integer isDeleted) {
		set("is_deleted", isDeleted);
	}
	
	public java.lang.Integer getIsDeleted() {
		return getInt("is_deleted");
	}
	
	public void setCreatedAt(java.util.Date createdAt) {
		set("created_at", createdAt);
	}
	
	public java.util.Date getCreatedAt() {
		return getDate("created_at");
	}
	
	public void setUpdatedAt(java.util.Date updatedAt) {
		set("updated_at", updatedAt);
	}
	
	public java.util.Date getUpdatedAt() {
		return getDate("updated_at");
	}
	
	/**
	 * 删除时间
	 */
	public void setDeletedTime(java.util.Date deletedTime) {
		set("deleted_time", deletedTime);
	}
	
	/**
	 * 删除时间
	 */
	public java.util.Date getDeletedTime() {
		return getDate("deleted_time");
	}
	
}

