package com.shopoperate.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseShops<M extends BaseShops<M>> extends Model<M> implements IBean {

	public void setId(java.math.BigInteger id) {
		set("id", id);
	}
	
	public java.math.BigInteger getId() {
		return getBigInteger("id");
	}
	
	/**
	 * 所属商户staff_id
	 */
	public void setOwnerStaffId(java.math.BigInteger ownerStaffId) {
		set("owner_staff_id", ownerStaffId);
	}
	
	/**
	 * 所属商户staff_id
	 */
	public java.math.BigInteger getOwnerStaffId() {
		return getBigInteger("owner_staff_id");
	}
	
	/**
	 * 关联席位ID
	 */
	public void setSeatId(java.math.BigInteger seatId) {
		set("seat_id", seatId);
	}
	
	/**
	 * 关联席位ID
	 */
	public java.math.BigInteger getSeatId() {
		return getBigInteger("seat_id");
	}
	
	/**
	 * 店铺名称
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	/**
	 * 店铺名称
	 */
	public java.lang.String getName() {
		return getStr("name");
	}
	
	/**
	 * 地址
	 */
	public void setAddress(java.lang.String address) {
		set("address", address);
	}
	
	/**
	 * 地址
	 */
	public java.lang.String getAddress() {
		return getStr("address");
	}
	
	/**
	 * 联系电话
	 */
	public void setContactPhone(java.lang.String contactPhone) {
		set("contact_phone", contactPhone);
	}
	
	/**
	 * 联系电话
	 */
	public java.lang.String getContactPhone() {
		return getStr("contact_phone");
	}
	
	/**
	 * 店铺最大客容量
	 */
	public void setMaxCapacity(java.lang.Long maxCapacity) {
		set("max_capacity", maxCapacity);
	}
	
	/**
	 * 店铺最大客容量
	 */
	public java.lang.Long getMaxCapacity() {
		return getLong("max_capacity");
	}
	
	/**
	 * 1-营业中，0-休息
	 */
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	/**
	 * 1-营业中，0-休息
	 */
	public java.lang.Integer getStatus() {
		return getInt("status");
	}
	
	/**
	 * 店铺描述
	 */
	public void setDescription(java.lang.String description) {
		set("description", description);
	}
	
	/**
	 * 店铺描述
	 */
	public java.lang.String getDescription() {
		return getStr("description");
	}
	
	/**
	 * 门头照片
	 */
	public void setSignPhoto(java.lang.String signPhoto) {
		set("sign_photo", signPhoto);
	}
	
	/**
	 * 门头照片
	 */
	public java.lang.String getSignPhoto() {
		return getStr("sign_photo");
	}
	
	public void setIsDeleted(java.lang.Integer isDeleted) {
		set("is_deleted", isDeleted);
	}
	
	public java.lang.Integer getIsDeleted() {
		return getInt("is_deleted");
	}
	
	public void setCreatedAt(java.util.Date createdAt) {
		set("created_at", createdAt);
	}
	
	public java.util.Date getCreatedAt() {
		return getDate("created_at");
	}
	
	public void setUpdatedAt(java.util.Date updatedAt) {
		set("updated_at", updatedAt);
	}
	
	public java.util.Date getUpdatedAt() {
		return getDate("updated_at");
	}
	
	/**
	 * 删除时间
	 */
	public void setDeletedTime(java.util.Date deletedTime) {
		set("deleted_time", deletedTime);
	}
	
	/**
	 * 删除时间
	 */
	public java.util.Date getDeletedTime() {
		return getDate("deleted_time");
	}
	
}

