package com.shopoperate.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDailySnapshots<M extends BaseDailySnapshots<M>> extends Model<M> implements IBean {

	public void setId(java.math.BigInteger id) {
		set("id", id);
	}
	
	public java.math.BigInteger getId() {
		return getBigInteger("id");
	}
	
	public void setShopId(java.math.BigInteger shopId) {
		set("shop_id", shopId);
	}
	
	public java.math.BigInteger getShopId() {
		return getBigInteger("shop_id");
	}
	
	public void setSnapshotDate(java.util.Date snapshotDate) {
		set("snapshot_date", snapshotDate);
	}
	
	public java.util.Date getSnapshotDate() {
		return getDate("snapshot_date");
	}
	
	public void setSalesTotal(java.math.BigDecimal salesTotal) {
		set("sales_total", salesTotal);
	}
	
	public java.math.BigDecimal getSalesTotal() {
		return getBigDecimal("sales_total");
	}
	
	public void setRevenueConfirmed(java.math.BigDecimal revenueConfirmed) {
		set("revenue_confirmed", revenueConfirmed);
	}
	
	public java.math.BigDecimal getRevenueConfirmed() {
		return getBigDecimal("revenue_confirmed");
	}
	
	public void setNewCustomers(java.lang.Long newCustomers) {
		set("new_customers", newCustomers);
	}
	
	public java.lang.Long getNewCustomers() {
		return getLong("new_customers");
	}
	
	public void setActiveSessions(java.lang.Long activeSessions) {
		set("active_sessions", activeSessions);
	}
	
	public java.lang.Long getActiveSessions() {
		return getLong("active_sessions");
	}
	
	/**
	 * 平均游玩时长（单位：分钟）
	 */
	public void setAverageDuration(java.lang.Long averageDuration) {
		set("average_duration", averageDuration);
	}
	
	/**
	 * 平均游玩时长（单位：分钟）
	 */
	public java.lang.Long getAverageDuration() {
		return getLong("average_duration");
	}
	
	public void setTopPackageId(java.math.BigInteger topPackageId) {
		set("top_package_id", topPackageId);
	}
	
	public java.math.BigInteger getTopPackageId() {
		return getBigInteger("top_package_id");
	}
	
	public void setInventoryWarns(java.lang.String inventoryWarns) {
		set("inventory_warns", inventoryWarns);
	}
	
	public java.lang.String getInventoryWarns() {
		return getStr("inventory_warns");
	}
	
	public void setCreatedAt(java.util.Date createdAt) {
		set("created_at", createdAt);
	}
	
	public java.util.Date getCreatedAt() {
		return getDate("created_at");
	}
	
}

