package com.shopoperate.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseStaffShops<M extends BaseStaffShops<M>> extends Model<M> implements IBean {

	public void setId(java.math.BigInteger id) {
		set("id", id);
	}
	
	public java.math.BigInteger getId() {
		return getBigInteger("id");
	}
	
	/**
	 * 员工ID
	 */
	public void setStaffId(java.math.BigInteger staffId) {
		set("staff_id", staffId);
	}
	
	/**
	 * 员工ID
	 */
	public java.math.BigInteger getStaffId() {
		return getBigInteger("staff_id");
	}
	
	/**
	 * 店铺ID
	 */
	public void setShopId(java.math.BigInteger shopId) {
		set("shop_id", shopId);
	}
	
	/**
	 * 店铺ID
	 */
	public java.math.BigInteger getShopId() {
		return getBigInteger("shop_id");
	}
	
	public void setCreatedAt(java.util.Date createdAt) {
		set("created_at", createdAt);
	}
	
	public java.util.Date getCreatedAt() {
		return getDate("created_at");
	}
	
}

