package com.shopoperate.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePackages<M extends BasePackages<M>> extends Model<M> implements IBean {

	public void setId(java.math.BigInteger id) {
		set("id", id);
	}
	
	public java.math.BigInteger getId() {
		return getBigInteger("id");
	}
	
	/**
	 * 店铺id
	 */
	public void setShopId(java.math.BigInteger shopId) {
		set("shop_id", shopId);
	}
	
	/**
	 * 店铺id
	 */
	public java.math.BigInteger getShopId() {
		return getBigInteger("shop_id");
	}
	
	/**
	 * 套餐名称
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	/**
	 * 套餐名称
	 */
	public java.lang.String getName() {
		return getStr("name");
	}
	
	/**
	 * 套餐类型: SINGLE-单次, WEEKLY-周卡, MONTHLY-月卡
	 */
	public void setType(java.lang.String type) {
		set("type", type);
	}
	
	/**
	 * 套餐类型: SINGLE-单次, WEEKLY-周卡, MONTHLY-月卡
	 */
	public java.lang.String getType() {
		return getStr("type");
	}
	
	/**
	 * 套餐时长
	 */
	public void setDurationMinutes(java.lang.Long durationMinutes) {
		set("duration_minutes", durationMinutes);
	}
	
	/**
	 * 套餐时长
	 */
	public java.lang.Long getDurationMinutes() {
		return getLong("duration_minutes");
	}
	
	/**
	 * 价格
	 */
	public void setPrice(java.math.BigDecimal price) {
		set("price", price);
	}
	
	/**
	 * 价格
	 */
	public java.math.BigDecimal getPrice() {
		return getBigDecimal("price");
	}
	
	/**
	 * 原价
	 */
	public void setOriginalPrice(java.math.BigDecimal originalPrice) {
		set("original_price", originalPrice);
	}
	
	/**
	 * 原价
	 */
	public java.math.BigDecimal getOriginalPrice() {
		return getBigDecimal("original_price");
	}
	
	/**
	 * 最大游玩人数
	 */
	public void setMaxPeoplePerSession(java.lang.Integer maxPeoplePerSession) {
		set("max_people_per_session", maxPeoplePerSession);
	}
	
	/**
	 * 最大游玩人数
	 */
	public java.lang.Integer getMaxPeoplePerSession() {
		return getInt("max_people_per_session");
	}
	
	/**
	 * 描述
	 */
	public void setDescription(java.lang.String description) {
		set("description", description);
	}
	
	/**
	 * 描述
	 */
	public java.lang.String getDescription() {
		return getStr("description");
	}
	
	/**
	 * 是否启用
	 */
	public void setIsActive(java.lang.Integer isActive) {
		set("is_active", isActive);
	}
	
	/**
	 * 是否启用
	 */
	public java.lang.Integer getIsActive() {
		return getInt("is_active");
	}
	
	public void setCreatedAt(java.util.Date createdAt) {
		set("created_at", createdAt);
	}
	
	public java.util.Date getCreatedAt() {
		return getDate("created_at");
	}
	
	public void setUpdatedAt(java.util.Date updatedAt) {
		set("updated_at", updatedAt);
	}
	
	public java.util.Date getUpdatedAt() {
		return getDate("updated_at");
	}
	
	/**
	 * 0-正常，1-已删除
	 */
	public void setIsDeleted(java.lang.Integer isDeleted) {
		set("is_deleted", isDeleted);
	}
	
	/**
	 * 0-正常，1-已删除
	 */
	public java.lang.Integer getIsDeleted() {
		return getInt("is_deleted");
	}
	
	/**
	 * 删除时间
	 */
	public void setDeletedTime(java.util.Date deletedTime) {
		set("deleted_time", deletedTime);
	}
	
	/**
	 * 删除时间
	 */
	public java.util.Date getDeletedTime() {
		return getDate("deleted_time");
	}
	
}

