package com.shopoperate.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseStaffAccounts<M extends BaseStaffAccounts<M>> extends Model<M> implements IBean {

	public void setId(java.math.BigInteger id) {
		set("id", id);
	}
	
	public java.math.BigInteger getId() {
		return getBigInteger("id");
	}
	
	public void setStaffId(java.math.BigInteger staffId) {
		set("staff_id", staffId);
	}
	
	public java.math.BigInteger getStaffId() {
		return getBigInteger("staff_id");
	}
	
	public void setUsername(java.lang.String username) {
		set("username", username);
	}
	
	public java.lang.String getUsername() {
		return getStr("username");
	}
	
	public void setPasswordHash(java.lang.String passwordHash) {
		set("password_hash", passwordHash);
	}
	
	public java.lang.String getPasswordHash() {
		return getStr("password_hash");
	}
	
	public void setWechatOpenid(java.lang.String wechatOpenid) {
		set("wechat_openid", wechatOpenid);
	}
	
	public java.lang.String getWechatOpenid() {
		return getStr("wechat_openid");
	}
	
	public void setLastLoginAt(java.util.Date lastLoginAt) {
		set("last_login_at", lastLoginAt);
	}
	
	public java.util.Date getLastLoginAt() {
		return getDate("last_login_at");
	}
	
	/**
	 * 是否删除（0-否，1-是）
	 */
	public void setIsDeleted(java.lang.Integer isDeleted) {
		set("is_deleted", isDeleted);
	}
	
	/**
	 * 是否删除（0-否，1-是）
	 */
	public java.lang.Integer getIsDeleted() {
		return getInt("is_deleted");
	}
	
	public void setCreatedAt(java.util.Date createdAt) {
		set("created_at", createdAt);
	}
	
	public java.util.Date getCreatedAt() {
		return getDate("created_at");
	}
	
	/**
	 * 删除时间
	 */
	public void setDeletedTime(java.util.Date deletedTime) {
		set("deleted_time", deletedTime);
	}
	
	/**
	 * 删除时间
	 */
	public java.util.Date getDeletedTime() {
		return getDate("deleted_time");
	}
	
}

