package com.shopoperate.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseQueueEntries<M extends BaseQueueEntries<M>> extends Model<M> implements IBean {

	public void setId(java.math.BigInteger id) {
		set("id", id);
	}
	
	public java.math.BigInteger getId() {
		return getBigInteger("id");
	}
	
	public void setShopId(java.math.BigInteger shopId) {
		set("shop_id", shopId);
	}
	
	public java.math.BigInteger getShopId() {
		return getBigInteger("shop_id");
	}
	
	public void setCustomerId(java.math.BigInteger customerId) {
		set("customer_id", customerId);
	}
	
	public java.math.BigInteger getCustomerId() {
		return getBigInteger("customer_id");
	}
	
	public void setQueueNumber(java.lang.Long queueNumber) {
		set("queue_number", queueNumber);
	}
	
	public java.lang.Long getQueueNumber() {
		return getLong("queue_number");
	}
	
	public void setPartySize(java.lang.Integer partySize) {
		set("party_size", partySize);
	}
	
	public java.lang.Integer getPartySize() {
		return getInt("party_size");
	}
	
	/**
	 * 状态: 1-排队中, 2-已入座, 3-已取消, 4-已通知
	 */
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	/**
	 * 状态: 1-排队中, 2-已入座, 3-已取消, 4-已通知
	 */
	public java.lang.Integer getStatus() {
		return getInt("status");
	}
	
	public void setRequestedAt(java.util.Date requestedAt) {
		set("requested_at", requestedAt);
	}
	
	public java.util.Date getRequestedAt() {
		return getDate("requested_at");
	}
	
	public void setSeatedAt(java.util.Date seatedAt) {
		set("seated_at", seatedAt);
	}
	
	public java.util.Date getSeatedAt() {
		return getDate("seated_at");
	}
	
	public void setNotifiedAt(java.util.Date notifiedAt) {
		set("notified_at", notifiedAt);
	}
	
	public java.util.Date getNotifiedAt() {
		return getDate("notified_at");
	}
	
	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}
	
	/**
	 * 0-正常，1-已删除
	 */
	public void setIsDeleted(java.lang.Integer isDeleted) {
		set("is_deleted", isDeleted);
	}
	
	/**
	 * 0-正常，1-已删除
	 */
	public java.lang.Integer getIsDeleted() {
		return getInt("is_deleted");
	}
	
	/**
	 * 删除时间
	 */
	public void setDeletedTime(java.util.Date deletedTime) {
		set("deleted_time", deletedTime);
	}
	
	/**
	 * 删除时间
	 */
	public java.util.Date getDeletedTime() {
		return getDate("deleted_time");
	}
	
}

