package com.shopoperate.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseExpenses<M extends BaseExpenses<M>> extends Model<M> implements IBean {

	public void setId(java.math.BigInteger id) {
		set("id", id);
	}
	
	public java.math.BigInteger getId() {
		return getBigInteger("id");
	}
	
	public void setShopId(java.math.BigInteger shopId) {
		set("shop_id", shopId);
	}
	
	public java.math.BigInteger getShopId() {
		return getBigInteger("shop_id");
	}
	
	public void setCategoryId(java.math.BigInteger categoryId) {
		set("category_id", categoryId);
	}
	
	public java.math.BigInteger getCategoryId() {
		return getBigInteger("category_id");
	}
	
	public void setAmount(java.math.BigDecimal amount) {
		set("amount", amount);
	}
	
	public java.math.BigDecimal getAmount() {
		return getBigDecimal("amount");
	}
	
	public void setPaymentMethod(java.lang.String paymentMethod) {
		set("payment_method", paymentMethod);
	}
	
	public java.lang.String getPaymentMethod() {
		return getStr("payment_method");
	}
	
	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}
	
	public void setExpenseDate(java.util.Date expenseDate) {
		set("expense_date", expenseDate);
	}
	
	public java.util.Date getExpenseDate() {
		return getDate("expense_date");
	}
	
	public void setCreatedAt(java.util.Date createdAt) {
		set("created_at", createdAt);
	}
	
	public java.util.Date getCreatedAt() {
		return getDate("created_at");
	}
	
	/**
	 * 0-正常，1-已删除
	 */
	public void setIsDeleted(java.lang.Integer isDeleted) {
		set("is_deleted", isDeleted);
	}
	
	/**
	 * 0-正常，1-已删除
	 */
	public java.lang.Integer getIsDeleted() {
		return getInt("is_deleted");
	}
	
	/**
	 * 删除时间
	 */
	public void setDeletedTime(java.util.Date deletedTime) {
		set("deleted_time", deletedTime);
	}
	
	/**
	 * 删除时间
	 */
	public java.util.Date getDeletedTime() {
		return getDate("deleted_time");
	}
	
	public void setSourceType(java.lang.String sourceType) {
		set("source_type", sourceType);
	}
	
	public java.lang.String getSourceType() {
		return getStr("source_type");
	}
	
	public void setSourceId(java.lang.Long sourceId) {
		set("source_id", sourceId);
	}
	
	public java.lang.Long getSourceId() {
		return getLong("source_id");
	}
	
	public void setOperatorStaffId(java.lang.Long operatorStaffId) {
		set("operator_staff_id", operatorStaffId);
	}
	
	public java.lang.Long getOperatorStaffId() {
		return getLong("operator_staff_id");
	}
	
}

