package com.shopoperate.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseStaffRoles<M extends BaseStaffRoles<M>> extends Model<M> implements IBean {

	public void setStaffId(java.math.BigInteger staffId) {
		set("staff_id", staffId);
	}
	
	public java.math.BigInteger getStaffId() {
		return getBigInteger("staff_id");
	}
	
	public void setRoleId(java.math.BigInteger roleId) {
		set("role_id", roleId);
	}
	
	public java.math.BigInteger getRoleId() {
		return getBigInteger("role_id");
	}
	
}

