package com.shopoperate.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCustomers<M extends BaseCustomers<M>> extends Model<M> implements IBean {

	public void setId(java.math.BigInteger id) {
		set("id", id);
	}
	
	public java.math.BigInteger getId() {
		return getBigInteger("id");
	}
	
	/**
	 * 店铺id
	 */
	public void setShopId(java.math.BigInteger shopId) {
		set("shop_id", shopId);
	}
	
	/**
	 * 店铺id
	 */
	public java.math.BigInteger getShopId() {
		return getBigInteger("shop_id");
	}
	
	/**
	 * 昵称
	 */
	public void setNickname(java.lang.String nickname) {
		set("nickname", nickname);
	}
	
	/**
	 * 昵称
	 */
	public java.lang.String getNickname() {
		return getStr("nickname");
	}
	
	/**
	 * 头像
	 */
	public void setAvatarUrl(java.lang.String avatarUrl) {
		set("avatar_url", avatarUrl);
	}
	
	/**
	 * 头像
	 */
	public java.lang.String getAvatarUrl() {
		return getStr("avatar_url");
	}
	
	/**
	 * 手机号
	 */
	public void setPhone(java.lang.String phone) {
		set("phone", phone);
	}
	
	/**
	 * 手机号
	 */
	public java.lang.String getPhone() {
		return getStr("phone");
	}
	
	/**
	 * 0-未知，1-男，2-女
	 */
	public void setGender(java.lang.Integer gender) {
		set("gender", gender);
	}
	
	/**
	 * 0-未知，1-男，2-女
	 */
	public java.lang.Integer getGender() {
		return getInt("gender");
	}
	
	/**
	 * 生日
	 */
	public void setBirthday(java.util.Date birthday) {
		set("birthday", birthday);
	}
	
	/**
	 * 生日
	 */
	public java.util.Date getBirthday() {
		return getDate("birthday");
	}
	
	public void setWechatOpenid(java.lang.String wechatOpenid) {
		set("wechat_openid", wechatOpenid);
	}
	
	public java.lang.String getWechatOpenid() {
		return getStr("wechat_openid");
	}
	
	public void setWechatUnionid(java.lang.String wechatUnionid) {
		set("wechat_unionid", wechatUnionid);
	}
	
	public java.lang.String getWechatUnionid() {
		return getStr("wechat_unionid");
	}
	
	/**
	 * 来源 store/meituan/douyin/other
	 */
	public void setSource(java.lang.String source) {
		set("source", source);
	}
	
	/**
	 * 来源 store/meituan/douyin/other
	 */
	public java.lang.String getSource() {
		return getStr("source");
	}
	
	/**
	 * 标签，逗号分隔
	 */
	public void setTags(java.lang.String tags) {
		set("tags", tags);
	}
	
	/**
	 * 标签，逗号分隔
	 */
	public java.lang.String getTags() {
		return getStr("tags");
	}
	
	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}
	
	public void setIsDeleted(java.lang.Integer isDeleted) {
		set("is_deleted", isDeleted);
	}
	
	public java.lang.Integer getIsDeleted() {
		return getInt("is_deleted");
	}
	
	public void setCreatedAt(java.util.Date createdAt) {
		set("created_at", createdAt);
	}
	
	public java.util.Date getCreatedAt() {
		return getDate("created_at");
	}
	
	public void setUpdatedAt(java.util.Date updatedAt) {
		set("updated_at", updatedAt);
	}
	
	public java.util.Date getUpdatedAt() {
		return getDate("updated_at");
	}
	
	/**
	 * 删除时间
	 */
	public void setDeletedTime(java.util.Date deletedTime) {
		set("deleted_time", deletedTime);
	}
	
	/**
	 * 删除时间
	 */
	public java.util.Date getDeletedTime() {
		return getDate("deleted_time");
	}
	
}

