package com.shopoperate.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSeatSubscriptions<M extends BaseSeatSubscriptions<M>> extends Model<M> implements IBean {

	public void setId(java.math.BigInteger id) {
		set("id", id);
	}
	
	public java.math.BigInteger getId() {
		return getBigInteger("id");
	}
	
	/**
	 * 席位号
	 */
	public void setSeatNo(java.lang.String seatNo) {
		set("seat_no", seatNo);
	}
	
	/**
	 * 席位号
	 */
	public java.lang.String getSeatNo() {
		return getStr("seat_no");
	}
	
	/**
	 * staff表的id
	 */
	public void setStaffId(java.math.BigInteger staffId) {
		set("staff_id", staffId);
	}
	
	/**
	 * staff表的id
	 */
	public java.math.BigInteger getStaffId() {
		return getBigInteger("staff_id");
	}
	
	/**
	 * 生效日期
	 */
	public void setStartDate(java.util.Date startDate) {
		set("start_date", startDate);
	}
	
	/**
	 * 生效日期
	 */
	public java.util.Date getStartDate() {
		return getDate("start_date");
	}
	
	/**
	 * 到期日期
	 */
	public void setEndDate(java.util.Date endDate) {
		set("end_date", endDate);
	}
	
	/**
	 * 到期日期
	 */
	public java.util.Date getEndDate() {
		return getDate("end_date");
	}
	
	/**
	 * 状态: 1-生效中 2-已到期
	 */
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	/**
	 * 状态: 1-生效中 2-已到期
	 */
	public java.lang.Integer getStatus() {
		return getInt("status");
	}
	
	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}
	
	public void setCreatedAt(java.util.Date createdAt) {
		set("created_at", createdAt);
	}
	
	public java.util.Date getCreatedAt() {
		return getDate("created_at");
	}
	
	public void setUpdatedAt(java.util.Date updatedAt) {
		set("updated_at", updatedAt);
	}
	
	public java.util.Date getUpdatedAt() {
		return getDate("updated_at");
	}
	
}

