package com.shopoperate.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseStaffSchedules<M extends BaseStaffSchedules<M>> extends Model<M> implements IBean {

	public void setId(java.math.BigInteger id) {
		set("id", id);
	}
	
	public java.math.BigInteger getId() {
		return getBigInteger("id");
	}
	
	public void setShopId(java.math.BigInteger shopId) {
		set("shop_id", shopId);
	}
	
	public java.math.BigInteger getShopId() {
		return getBigInteger("shop_id");
	}
	
	public void setStaffId(java.math.BigInteger staffId) {
		set("staff_id", staffId);
	}
	
	public java.math.BigInteger getStaffId() {
		return getBigInteger("staff_id");
	}
	
	public void setScheduleDate(java.util.Date scheduleDate) {
		set("schedule_date", scheduleDate);
	}
	
	public java.util.Date getScheduleDate() {
		return getDate("schedule_date");
	}
	
	public void setStartTime(java.sql.Time startTime) {
		set("start_time", startTime);
	}
	
	public java.sql.Time getStartTime() {
		return get("start_time");
	}
	
	public void setEndTime(java.sql.Time endTime) {
		set("end_time", endTime);
	}
	
	public java.sql.Time getEndTime() {
		return get("end_time");
	}
	
	/**
	 * 班次: 1-上班, 2-休息
	 */
	public void setType(java.lang.Integer type) {
		set("type", type);
	}
	
	/**
	 * 班次: 1-上班, 2-休息
	 */
	public java.lang.Integer getType() {
		return getInt("type");
	}
	
	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}
	
	public void setCreatedAt(java.util.Date createdAt) {
		set("created_at", createdAt);
	}
	
	public java.util.Date getCreatedAt() {
		return getDate("created_at");
	}
	
}

