package com.shopoperate.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGameSessions<M extends BaseGameSessions<M>> extends Model<M> implements IBean {

	public void setId(java.math.BigInteger id) {
		set("id", id);
	}
	
	public java.math.BigInteger getId() {
		return getBigInteger("id");
	}
	
	public void setShopId(java.math.BigInteger shopId) {
		set("shop_id", shopId);
	}
	
	public java.math.BigInteger getShopId() {
		return getBigInteger("shop_id");
	}
	
	public void setCustomerId(java.math.BigInteger customerId) {
		set("customer_id", customerId);
	}
	
	public java.math.BigInteger getCustomerId() {
		return getBigInteger("customer_id");
	}
	
	public void setCustomerSessionId(java.math.BigInteger customerSessionId) {
		set("customer_session_id", customerSessionId);
	}
	
	public java.math.BigInteger getCustomerSessionId() {
		return getBigInteger("customer_session_id");
	}
	
	public void setStaffId(java.math.BigInteger staffId) {
		set("staff_id", staffId);
	}
	
	public java.math.BigInteger getStaffId() {
		return getBigInteger("staff_id");
	}
	
	public void setStartTime(java.util.Date startTime) {
		set("start_time", startTime);
	}
	
	public java.util.Date getStartTime() {
		return getDate("start_time");
	}
	
	public void setEndTime(java.util.Date endTime) {
		set("end_time", endTime);
	}
	
	public java.util.Date getEndTime() {
		return getDate("end_time");
	}
	
	/**
	 * 状态: 1-进行中, 2-已完成, 3-已取消
	 */
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	/**
	 * 状态: 1-进行中, 2-已完成, 3-已取消
	 */
	public java.lang.Integer getStatus() {
		return getInt("status");
	}
	
	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}
	
	public void setCreatedAt(java.util.Date createdAt) {
		set("created_at", createdAt);
	}
	
	public java.util.Date getCreatedAt() {
		return getDate("created_at");
	}
	
	/**
	 * 0-正常，1-已删除
	 */
	public void setIsDeleted(java.lang.Integer isDeleted) {
		set("is_deleted", isDeleted);
	}
	
	/**
	 * 0-正常，1-已删除
	 */
	public java.lang.Integer getIsDeleted() {
		return getInt("is_deleted");
	}
	
	/**
	 * 删除时间
	 */
	public void setDeletedTime(java.util.Date deletedTime) {
		set("deleted_time", deletedTime);
	}
	
	/**
	 * 删除时间
	 */
	public java.util.Date getDeletedTime() {
		return getDate("deleted_time");
	}
	
}

