package com.shopoperate.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePermissions<M extends BasePermissions<M>> extends Model<M> implements IBean {

	public void setId(java.math.BigInteger id) {
		set("id", id);
	}
	
	public java.math.BigInteger getId() {
		return getBigInteger("id");
	}
	
	/**
	 * 父级ID（0=顶级）
	 */
	public void setParentId(java.math.BigInteger parentId) {
		set("parent_id", parentId);
	}
	
	/**
	 * 父级ID（0=顶级）
	 */
	public java.math.BigInteger getParentId() {
		return getBigInteger("parent_id");
	}
	
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}
	
	public void setMenuCode(java.lang.String menuCode) {
		set("menu_code", menuCode);
	}
	
	public java.lang.String getMenuCode() {
		return getStr("menu_code");
	}
	
	/**
	 * 路由路径
	 */
	public void setPath(java.lang.String path) {
		set("path", path);
	}
	
	/**
	 * 路由路径
	 */
	public java.lang.String getPath() {
		return getStr("path");
	}
	
	/**
	 * 组件路径（如 /src/views/xxx/index.vue）
	 */
	public void setComponent(java.lang.String component) {
		set("component", component);
	}
	
	/**
	 * 组件路径（如 /src/views/xxx/index.vue）
	 */
	public java.lang.String getComponent() {
		return getStr("component");
	}
	
	/**
	 * 重定向路径
	 */
	public void setRedirect(java.lang.String redirect) {
		set("redirect", redirect);
	}
	
	/**
	 * 重定向路径
	 */
	public java.lang.String getRedirect() {
		return getStr("redirect");
	}
	
	/**
	 * 菜单图标
	 */
	public void setIcon(java.lang.String icon) {
		set("icon", icon);
	}
	
	/**
	 * 菜单图标
	 */
	public java.lang.String getIcon() {
		return getStr("icon");
	}
	
	/**
	 * 排序（rank）
	 */
	public void setSort(java.lang.Long sort) {
		set("sort", sort);
	}
	
	/**
	 * 排序（rank）
	 */
	public java.lang.Long getSort() {
		return getLong("sort");
	}
	
	/**
	 * 类型：1-目录 2-菜单 3-按钮
	 */
	public void setType(java.lang.Integer type) {
		set("type", type);
	}
	
	/**
	 * 类型：1-目录 2-菜单 3-按钮
	 */
	public java.lang.Integer getType() {
		return getInt("type");
	}
	
	public void setDescription(java.lang.String description) {
		set("description", description);
	}
	
	public java.lang.String getDescription() {
		return getStr("description");
	}
	
	/**
	 * 是否启用
	 */
	public void setIsActive(java.lang.Integer isActive) {
		set("is_active", isActive);
	}
	
	/**
	 * 是否启用
	 */
	public java.lang.Integer getIsActive() {
		return getInt("is_active");
	}
	
	/**
	 * 是否删除
	 */
	public void setIsDeleted(java.lang.Integer isDeleted) {
		set("is_deleted", isDeleted);
	}
	
	/**
	 * 是否删除
	 */
	public java.lang.Integer getIsDeleted() {
		return getInt("is_deleted");
	}
	
	/**
	 * 超管菜单可见：0-否，1-是
	 */
	public void setSuperAdminVisible(java.lang.Integer superAdminVisible) {
		set("super_admin_visible", superAdminVisible);
	}
	
	/**
	 * 超管菜单可见：0-否，1-是
	 */
	public java.lang.Integer getSuperAdminVisible() {
		return getInt("super_admin_visible");
	}
	
	public void setCreatedAt(java.util.Date createdAt) {
		set("created_at", createdAt);
	}
	
	public java.util.Date getCreatedAt() {
		return getDate("created_at");
	}
	
	/**
	 * 更新时间
	 */
	public void setUpdatedAt(java.util.Date updatedAt) {
		set("updated_at", updatedAt);
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdatedAt() {
		return getDate("updated_at");
	}
	
}

