package com.shopoperate.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSeatSubscriptionsTransactions<M extends BaseSeatSubscriptionsTransactions<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}
	
	/**
	 * seat_subscripitions表id
	 */
	public void setSeatId(java.lang.Long seatId) {
		set("seat_id", seatId);
	}
	
	/**
	 * seat_subscripitions表id
	 */
	public java.lang.Long getSeatId() {
		return getLong("seat_id");
	}
	
	/**
	 * 支付金额
	 */
	public void setAmount(java.math.BigDecimal amount) {
		set("amount", amount);
	}
	
	/**
	 * 支付金额
	 */
	public java.math.BigDecimal getAmount() {
		return getBigDecimal("amount");
	}
	
	/**
	 * 支付方式: 微信：wechat/支付宝：alipay/银行转账：bank/现金：cash/其他：other
	 */
	public void setPaymentMethod(java.lang.String paymentMethod) {
		set("payment_method", paymentMethod);
	}
	
	/**
	 * 支付方式: 微信：wechat/支付宝：alipay/银行转账：bank/现金：cash/其他：other
	 */
	public java.lang.String getPaymentMethod() {
		return getStr("payment_method");
	}
	
	/**
	 * 支付流水号
	 */
	public void setPaymentNo(java.lang.String paymentNo) {
		set("payment_no", paymentNo);
	}
	
	/**
	 * 支付流水号
	 */
	public java.lang.String getPaymentNo() {
		return getStr("payment_no");
	}
	
	/**
	 * 订阅类型: 1-月付 2-年付
	 */
	public void setSubscriptionType(java.lang.Integer subscriptionType) {
		set("subscription_type", subscriptionType);
	}
	
	/**
	 * 订阅类型: 1-月付 2-年付
	 */
	public java.lang.Integer getSubscriptionType() {
		return getInt("subscription_type");
	}
	
	/**
	 * 订阅次数
	 */
	public void setSubscriptionNum(java.lang.Integer subscriptionNum) {
		set("subscription_num", subscriptionNum);
	}
	
	/**
	 * 订阅次数
	 */
	public java.lang.Integer getSubscriptionNum() {
		return getInt("subscription_num");
	}
	
	/**
	 * 状态: 1-支付 2-退款
	 */
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	/**
	 * 状态: 1-支付 2-退款
	 */
	public java.lang.Integer getStatus() {
		return getInt("status");
	}
	
	/**
	 * 退款金额
	 */
	public void setRefundAmount(java.math.BigDecimal refundAmount) {
		set("refund_amount", refundAmount);
	}
	
	/**
	 * 退款金额
	 */
	public java.math.BigDecimal getRefundAmount() {
		return getBigDecimal("refund_amount");
	}
	
	/**
	 * 退款扣除天数
	 */
	public void setRefundDays(java.lang.Integer refundDays) {
		set("refund_days", refundDays);
	}
	
	/**
	 * 退款扣除天数
	 */
	public java.lang.Integer getRefundDays() {
		return getInt("refund_days");
	}
	
	public void setCreatedAt(java.util.Date createdAt) {
		set("created_at", createdAt);
	}
	
	public java.util.Date getCreatedAt() {
		return getDate("created_at");
	}
	
}

