package com.shopoperate.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePurchasePayments<M extends BasePurchasePayments<M>> extends Model<M> implements IBean {

	public void setId(java.math.BigInteger id) {
		set("id", id);
	}
	
	public java.math.BigInteger getId() {
		return getBigInteger("id");
	}
	
	public void setPurchaseOrderId(java.math.BigInteger purchaseOrderId) {
		set("purchase_order_id", purchaseOrderId);
	}
	
	public java.math.BigInteger getPurchaseOrderId() {
		return getBigInteger("purchase_order_id");
	}
	
	public void setAmount(java.math.BigDecimal amount) {
		set("amount", amount);
	}
	
	public java.math.BigDecimal getAmount() {
		return getBigDecimal("amount");
	}
	
	public void setPaymentMethod(java.lang.String paymentMethod) {
		set("payment_method", paymentMethod);
	}
	
	public java.lang.String getPaymentMethod() {
		return getStr("payment_method");
	}
	
	public void setPaidAt(java.util.Date paidAt) {
		set("paid_at", paidAt);
	}
	
	public java.util.Date getPaidAt() {
		return getDate("paid_at");
	}
	
	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}
	
	public void setCreatedAt(java.util.Date createdAt) {
		set("created_at", createdAt);
	}
	
	public java.util.Date getCreatedAt() {
		return getDate("created_at");
	}
	
	/**
	 * 0-正常，1-已删除
	 */
	public void setIsDeleted(java.lang.Integer isDeleted) {
		set("is_deleted", isDeleted);
	}
	
	/**
	 * 0-正常，1-已删除
	 */
	public java.lang.Integer getIsDeleted() {
		return getInt("is_deleted");
	}
	
	/**
	 * 删除时间
	 */
	public void setDeletedTime(java.util.Date deletedTime) {
		set("deleted_time", deletedTime);
	}
	
	/**
	 * 删除时间
	 */
	public java.util.Date getDeletedTime() {
		return getDate("deleted_time");
	}
	
	/**
	 * 关联支出记录ID
	 */
	public void setExpenseId(java.lang.Long expenseId) {
		set("expense_id", expenseId);
	}
	
	/**
	 * 关联支出记录ID
	 */
	public java.lang.Long getExpenseId() {
		return getLong("expense_id");
	}
	
}

