package com.shopoperate.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseShopFaqs<M extends BaseShopFaqs<M>> extends Model<M> implements IBean {

	public void setId(java.math.BigInteger id) {
		set("id", id);
	}
	
	public java.math.BigInteger getId() {
		return getBigInteger("id");
	}
	
	/**
	 * 店铺ID
	 */
	public void setShopId(java.math.BigInteger shopId) {
		set("shop_id", shopId);
	}
	
	/**
	 * 店铺ID
	 */
	public java.math.BigInteger getShopId() {
		return getBigInteger("shop_id");
	}
	
	/**
	 * 问题
	 */
	public void setQuestion(java.lang.String question) {
		set("question", question);
	}
	
	/**
	 * 问题
	 */
	public java.lang.String getQuestion() {
		return getStr("question");
	}
	
	/**
	 * 回答
	 */
	public void setAnswer(java.lang.String answer) {
		set("answer", answer);
	}
	
	/**
	 * 回答
	 */
	public java.lang.String getAnswer() {
		return getStr("answer");
	}
	
	/**
	 * 分类(general/pricing/refund/rules)
	 */
	public void setCategory(java.lang.String category) {
		set("category", category);
	}
	
	/**
	 * 分类(general/pricing/refund/rules)
	 */
	public java.lang.String getCategory() {
		return getStr("category");
	}
	
	/**
	 * 排序
	 */
	public void setSortOrder(java.lang.Long sortOrder) {
		set("sort_order", sortOrder);
	}
	
	/**
	 * 排序
	 */
	public java.lang.Long getSortOrder() {
		return getLong("sort_order");
	}
	
	/**
	 * 是否启用
	 */
	public void setIsActive(java.lang.Integer isActive) {
		set("is_active", isActive);
	}
	
	/**
	 * 是否启用
	 */
	public java.lang.Integer getIsActive() {
		return getInt("is_active");
	}
	
	public void setCreatedAt(java.util.Date createdAt) {
		set("created_at", createdAt);
	}
	
	public java.util.Date getCreatedAt() {
		return getDate("created_at");
	}
	
	public void setUpdatedAt(java.util.Date updatedAt) {
		set("updated_at", updatedAt);
	}
	
	public java.util.Date getUpdatedAt() {
		return getDate("updated_at");
	}
	
}

