package com.shopoperate.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePurchaseOrders<M extends BasePurchaseOrders<M>> extends Model<M> implements IBean {

	public void setId(java.math.BigInteger id) {
		set("id", id);
	}
	
	public java.math.BigInteger getId() {
		return getBigInteger("id");
	}
	
	public void setShopId(java.math.BigInteger shopId) {
		set("shop_id", shopId);
	}
	
	public java.math.BigInteger getShopId() {
		return getBigInteger("shop_id");
	}
	
	public void setSupplierId(java.math.BigInteger supplierId) {
		set("supplier_id", supplierId);
	}
	
	public java.math.BigInteger getSupplierId() {
		return getBigInteger("supplier_id");
	}
	
	public void setOrderNumber(java.lang.String orderNumber) {
		set("order_number", orderNumber);
	}
	
	public java.lang.String getOrderNumber() {
		return getStr("order_number");
	}
	
	public void setOrderDate(java.util.Date orderDate) {
		set("order_date", orderDate);
	}
	
	public java.util.Date getOrderDate() {
		return getDate("order_date");
	}
	
	/**
	 * 结算方式: 1-现结, 2-赊账
	 */
	public void setType(java.lang.Integer type) {
		set("type", type);
	}
	
	/**
	 * 结算方式: 1-现结, 2-赊账
	 */
	public java.lang.Integer getType() {
		return getInt("type");
	}
	
	public void setTotalAmount(java.math.BigDecimal totalAmount) {
		set("total_amount", totalAmount);
	}
	
	public java.math.BigDecimal getTotalAmount() {
		return getBigDecimal("total_amount");
	}
	
	public void setPaidAmount(java.math.BigDecimal paidAmount) {
		set("paid_amount", paidAmount);
	}
	
	public java.math.BigDecimal getPaidAmount() {
		return getBigDecimal("paid_amount");
	}
	
	/**
	 * 状态: 1-进行中, 2-已完成, 3-已取消
	 */
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	/**
	 * 状态: 1-进行中, 2-已完成, 3-已取消
	 */
	public java.lang.Integer getStatus() {
		return getInt("status");
	}
	
	public void setOperatorStaffId(java.math.BigInteger operatorStaffId) {
		set("operator_staff_id", operatorStaffId);
	}
	
	public java.math.BigInteger getOperatorStaffId() {
		return getBigInteger("operator_staff_id");
	}
	
	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}
	
	public void setCreatedAt(java.util.Date createdAt) {
		set("created_at", createdAt);
	}
	
	public java.util.Date getCreatedAt() {
		return getDate("created_at");
	}
	
	public void setUpdatedAt(java.util.Date updatedAt) {
		set("updated_at", updatedAt);
	}
	
	public java.util.Date getUpdatedAt() {
		return getDate("updated_at");
	}
	
	/**
	 * 0-正常，1-已删除
	 */
	public void setIsDeleted(java.lang.Integer isDeleted) {
		set("is_deleted", isDeleted);
	}
	
	/**
	 * 0-正常，1-已删除
	 */
	public java.lang.Integer getIsDeleted() {
		return getInt("is_deleted");
	}
	
	/**
	 * 删除时间
	 */
	public void setDeletedTime(java.util.Date deletedTime) {
		set("deleted_time", deletedTime);
	}
	
	/**
	 * 删除时间
	 */
	public java.util.Date getDeletedTime() {
		return getDate("deleted_time");
	}
	
}

