package com.shopoperate.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseArticles<M extends BaseArticles<M>> extends Model<M> implements IBean {

	public void setId(java.math.BigInteger id) {
		set("id", id);
	}
	
	public java.math.BigInteger getId() {
		return getBigInteger("id");
	}
	
	public void setShopId(java.math.BigInteger shopId) {
		set("shop_id", shopId);
	}
	
	public java.math.BigInteger getShopId() {
		return getBigInteger("shop_id");
	}
	
	public void setCategoryId(java.math.BigInteger categoryId) {
		set("category_id", categoryId);
	}
	
	public java.math.BigInteger getCategoryId() {
		return getBigInteger("category_id");
	}
	
	public void setTitle(java.lang.String title) {
		set("title", title);
	}
	
	public java.lang.String getTitle() {
		return getStr("title");
	}
	
	/**
	 * 内容类型: 1-图片, 2-视频, 3-富文本
	 */
	public void setContentType(java.lang.Integer contentType) {
		set("content_type", contentType);
	}
	
	/**
	 * 内容类型: 1-图片, 2-视频, 3-富文本
	 */
	public java.lang.Integer getContentType() {
		return getInt("content_type");
	}
	
	public void setImageUrls(java.lang.String imageUrls) {
		set("image_urls", imageUrls);
	}
	
	public java.lang.String getImageUrls() {
		return getStr("image_urls");
	}
	
	public void setVideoUrl(java.lang.String videoUrl) {
		set("video_url", videoUrl);
	}
	
	public java.lang.String getVideoUrl() {
		return getStr("video_url");
	}
	
	public void setContent(java.lang.String content) {
		set("content", content);
	}
	
	public java.lang.String getContent() {
		return getStr("content");
	}
	
	public void setCoverImage(java.lang.String coverImage) {
		set("cover_image", coverImage);
	}
	
	public java.lang.String getCoverImage() {
		return getStr("cover_image");
	}
	
	public void setIsPublished(java.lang.Integer isPublished) {
		set("is_published", isPublished);
	}
	
	public java.lang.Integer getIsPublished() {
		return getInt("is_published");
	}
	
	public void setPublishedAt(java.util.Date publishedAt) {
		set("published_at", publishedAt);
	}
	
	public java.util.Date getPublishedAt() {
		return getDate("published_at");
	}
	
	public void setRelatedPackageIds(java.lang.String relatedPackageIds) {
		set("related_package_ids", relatedPackageIds);
	}
	
	public java.lang.String getRelatedPackageIds() {
		return getStr("related_package_ids");
	}
	
	public void setRelatedMaterialIds(java.lang.String relatedMaterialIds) {
		set("related_material_ids", relatedMaterialIds);
	}
	
	public java.lang.String getRelatedMaterialIds() {
		return getStr("related_material_ids");
	}
	
	public void setIsDeleted(java.lang.Integer isDeleted) {
		set("is_deleted", isDeleted);
	}
	
	public java.lang.Integer getIsDeleted() {
		return getInt("is_deleted");
	}
	
	public void setCreatedAt(java.util.Date createdAt) {
		set("created_at", createdAt);
	}
	
	public java.util.Date getCreatedAt() {
		return getDate("created_at");
	}
	
	public void setUpdatedAt(java.util.Date updatedAt) {
		set("updated_at", updatedAt);
	}
	
	public java.util.Date getUpdatedAt() {
		return getDate("updated_at");
	}
	
	/**
	 * 删除时间
	 */
	public void setDeletedTime(java.util.Date deletedTime) {
		set("deleted_time", deletedTime);
	}
	
	/**
	 * 删除时间
	 */
	public java.util.Date getDeletedTime() {
		return getDate("deleted_time");
	}
	
}

