package com.shopoperate.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseStaff<M extends BaseStaff<M>> extends Model<M> implements IBean {

	public void setId(java.math.BigInteger id) {
		set("id", id);
	}
	
	public java.math.BigInteger getId() {
		return getBigInteger("id");
	}
	
	/**
	 * 是否商户主体（0：否，1：是）
	 */
	public void setBossStatus(java.lang.Integer bossStatus) {
		set("boss_status", bossStatus);
	}
	
	/**
	 * 是否商户主体（0：否，1：是）
	 */
	public java.lang.Integer getBossStatus() {
		return getInt("boss_status");
	}
	
	/**
	 * 名称
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	/**
	 * 名称
	 */
	public java.lang.String getName() {
		return getStr("name");
	}
	
	/**
	 * 联系电话
	 */
	public void setPhone(java.lang.String phone) {
		set("phone", phone);
	}
	
	/**
	 * 联系电话
	 */
	public java.lang.String getPhone() {
		return getStr("phone");
	}
	
	/**
	 * 邮箱
	 */
	public void setContactEmail(java.lang.String contactEmail) {
		set("contact_email", contactEmail);
	}
	
	/**
	 * 邮箱
	 */
	public java.lang.String getContactEmail() {
		return getStr("contact_email");
	}
	
	/**
	 * 身份证
	 */
	public void setIdCard(java.lang.String idCard) {
		set("id_card", idCard);
	}
	
	/**
	 * 身份证
	 */
	public java.lang.String getIdCard() {
		return getStr("id_card");
	}
	
	/**
	 * 头像
	 */
	public void setAvatar(java.lang.String avatar) {
		set("avatar", avatar);
	}
	
	/**
	 * 头像
	 */
	public java.lang.String getAvatar() {
		return getStr("avatar");
	}
	
	/**
	 * 用工类型: 1-全职, 2-兼职
	 */
	public void setEmploymentType(java.lang.Integer employmentType) {
		set("employment_type", employmentType);
	}
	
	/**
	 * 用工类型: 1-全职, 2-兼职
	 */
	public java.lang.Integer getEmploymentType() {
		return getInt("employment_type");
	}
	
	/**
	 * 最大席位数（购买数量）
	 */
	public void setMaxSeats(java.lang.Long maxSeats) {
		set("max_seats", maxSeats);
	}
	
	/**
	 * 最大席位数（购买数量）
	 */
	public java.lang.Long getMaxSeats() {
		return getLong("max_seats");
	}
	
	/**
	 * 已开通店铺数
	 */
	public void setUsedSeats(java.lang.Long usedSeats) {
		set("used_seats", usedSeats);
	}
	
	/**
	 * 已开通店铺数
	 */
	public java.lang.Long getUsedSeats() {
		return getLong("used_seats");
	}
	
	/**
	 * 备注
	 */
	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	/**
	 * 备注
	 */
	public java.lang.String getRemark() {
		return getStr("remark");
	}
	
	/**
	 * 1-在职，0-离职
	 */
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	/**
	 * 1-在职，0-离职
	 */
	public java.lang.Integer getStatus() {
		return getInt("status");
	}
	
	/**
	 * 是否封禁（0否，1是）
	 */
	public void setIsBan(java.lang.Integer isBan) {
		set("is_ban", isBan);
	}
	
	/**
	 * 是否封禁（0否，1是）
	 */
	public java.lang.Integer getIsBan() {
		return getInt("is_ban");
	}
	
	public void setIsDeleted(java.lang.Integer isDeleted) {
		set("is_deleted", isDeleted);
	}
	
	public java.lang.Integer getIsDeleted() {
		return getInt("is_deleted");
	}
	
	public void setCreatedAt(java.util.Date createdAt) {
		set("created_at", createdAt);
	}
	
	public java.util.Date getCreatedAt() {
		return getDate("created_at");
	}
	
	public void setUpdatedAt(java.util.Date updatedAt) {
		set("updated_at", updatedAt);
	}
	
	public java.util.Date getUpdatedAt() {
		return getDate("updated_at");
	}
	
	/**
	 * 删除时间
	 */
	public void setDeletedTime(java.util.Date deletedTime) {
		set("deleted_time", deletedTime);
	}
	
	/**
	 * 删除时间
	 */
	public java.util.Date getDeletedTime() {
		return getDate("deleted_time");
	}
	
}

