package com.shopoperate.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRevenueRecords<M extends BaseRevenueRecords<M>> extends Model<M> implements IBean {

	public void setId(java.math.BigInteger id) {
		set("id", id);
	}
	
	public java.math.BigInteger getId() {
		return getBigInteger("id");
	}
	
	public void setShopId(java.math.BigInteger shopId) {
		set("shop_id", shopId);
	}
	
	public java.math.BigInteger getShopId() {
		return getBigInteger("shop_id");
	}
	
	public void setGameSessionId(java.math.BigInteger gameSessionId) {
		set("game_session_id", gameSessionId);
	}
	
	public java.math.BigInteger getGameSessionId() {
		return getBigInteger("game_session_id");
	}
	
	public void setPurchaseId(java.math.BigInteger purchaseId) {
		set("purchase_id", purchaseId);
	}
	
	public java.math.BigInteger getPurchaseId() {
		return getBigInteger("purchase_id");
	}
	
	public void setAmount(java.math.BigDecimal amount) {
		set("amount", amount);
	}
	
	public java.math.BigDecimal getAmount() {
		return getBigDecimal("amount");
	}
	
	public void setConfirmedAt(java.util.Date confirmedAt) {
		set("confirmed_at", confirmedAt);
	}
	
	public java.util.Date getConfirmedAt() {
		return getDate("confirmed_at");
	}
	
	/**
	 * 确认收入员工ID（staff.id）
	 */
	public void setConfirmedBy(java.math.BigInteger confirmedBy) {
		set("confirmed_by", confirmedBy);
	}
	
	/**
	 * 确认收入员工ID（staff.id）
	 */
	public java.math.BigInteger getConfirmedBy() {
		return getBigInteger("confirmed_by");
	}
	
	public void setCreatedAt(java.util.Date createdAt) {
		set("created_at", createdAt);
	}
	
	public java.util.Date getCreatedAt() {
		return getDate("created_at");
	}
	
	/**
	 * 0-正常，1-已删除
	 */
	public void setIsDeleted(java.lang.Integer isDeleted) {
		set("is_deleted", isDeleted);
	}
	
	/**
	 * 0-正常，1-已删除
	 */
	public java.lang.Integer getIsDeleted() {
		return getInt("is_deleted");
	}
	
	/**
	 * 删除时间
	 */
	public void setDeletedTime(java.util.Date deletedTime) {
		set("deleted_time", deletedTime);
	}
	
	/**
	 * 删除时间
	 */
	public java.util.Date getDeletedTime() {
		return getDate("deleted_time");
	}
	
	public void setPaymentMethod(java.lang.String paymentMethod) {
		set("payment_method", paymentMethod);
	}
	
	public java.lang.String getPaymentMethod() {
		return getStr("payment_method");
	}
	
	public void setCustomerId(java.lang.Long customerId) {
		set("customer_id", customerId);
	}
	
	public java.lang.Long getCustomerId() {
		return getLong("customer_id");
	}
	
}

