package com.shopoperate.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAttendanceRecords<M extends BaseAttendanceRecords<M>> extends Model<M> implements IBean {

	public void setId(java.math.BigInteger id) {
		set("id", id);
	}
	
	public java.math.BigInteger getId() {
		return getBigInteger("id");
	}
	
	public void setShopId(java.math.BigInteger shopId) {
		set("shop_id", shopId);
	}
	
	public java.math.BigInteger getShopId() {
		return getBigInteger("shop_id");
	}
	
	public void setStaffId(java.math.BigInteger staffId) {
		set("staff_id", staffId);
	}
	
	public java.math.BigInteger getStaffId() {
		return getBigInteger("staff_id");
	}
	
	public void setCheckInTime(java.util.Date checkInTime) {
		set("check_in_time", checkInTime);
	}
	
	public java.util.Date getCheckInTime() {
		return getDate("check_in_time");
	}
	
	public void setCheckOutTime(java.util.Date checkOutTime) {
		set("check_out_time", checkOutTime);
	}
	
	public java.util.Date getCheckOutTime() {
		return getDate("check_out_time");
	}
	
	public void setDate(java.util.Date date) {
		set("date", date);
	}
	
	public java.util.Date getDate() {
		return getDate("date");
	}
	
	/**
	 * 状态: 1-正常, 2-迟到, 3-早退, 4-加班
	 */
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	/**
	 * 状态: 1-正常, 2-迟到, 3-早退, 4-加班
	 */
	public java.lang.Integer getStatus() {
		return getInt("status");
	}
	
	public void setCreatedAt(java.util.Date createdAt) {
		set("created_at", createdAt);
	}
	
	public java.util.Date getCreatedAt() {
		return getDate("created_at");
	}
	
}

