package com.shopoperate.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCouponVerificationLogs<M extends BaseCouponVerificationLogs<M>> extends Model<M> implements IBean {

	public void setId(java.math.BigInteger id) {
		set("id", id);
	}
	
	public java.math.BigInteger getId() {
		return getBigInteger("id");
	}
	
	public void setShopId(java.math.BigInteger shopId) {
		set("shop_id", shopId);
	}
	
	public java.math.BigInteger getShopId() {
		return getBigInteger("shop_id");
	}
	
	public void setPurchaseId(java.math.BigInteger purchaseId) {
		set("purchase_id", purchaseId);
	}
	
	public java.math.BigInteger getPurchaseId() {
		return getBigInteger("purchase_id");
	}
	
	public void setThirdPartyCouponCode(java.lang.String thirdPartyCouponCode) {
		set("third_party_coupon_code", thirdPartyCouponCode);
	}
	
	public java.lang.String getThirdPartyCouponCode() {
		return getStr("third_party_coupon_code");
	}
	
	public void setChannel(java.lang.String channel) {
		set("channel", channel);
	}
	
	public java.lang.String getChannel() {
		return getStr("channel");
	}
	
	/**
	 * 操作: 1-注册, 2-核销, 3-同步
	 */
	public void setOperation(java.lang.Integer operation) {
		set("operation", operation);
	}
	
	/**
	 * 操作: 1-注册, 2-核销, 3-同步
	 */
	public java.lang.Integer getOperation() {
		return getInt("operation");
	}
	
	/**
	 * 结果: 1-成功, 2-失败, 3-无效码, 4-重复, 5-已过期
	 */
	public void setResult(java.lang.Integer result) {
		set("result", result);
	}
	
	/**
	 * 结果: 1-成功, 2-失败, 3-无效码, 4-重复, 5-已过期
	 */
	public java.lang.Integer getResult() {
		return getInt("result");
	}
	
	public void setErrorMessage(java.lang.String errorMessage) {
		set("error_message", errorMessage);
	}
	
	public java.lang.String getErrorMessage() {
		return getStr("error_message");
	}
	
	public void setOperatorStaffId(java.math.BigInteger operatorStaffId) {
		set("operator_staff_id", operatorStaffId);
	}
	
	public java.math.BigInteger getOperatorStaffId() {
		return getBigInteger("operator_staff_id");
	}
	
	public void setCreatedAt(java.util.Date createdAt) {
		set("created_at", createdAt);
	}
	
	public java.util.Date getCreatedAt() {
		return getDate("created_at");
	}
	
	/**
	 * 0-正常，1-已删除
	 */
	public void setIsDeleted(java.lang.Integer isDeleted) {
		set("is_deleted", isDeleted);
	}
	
	/**
	 * 0-正常，1-已删除
	 */
	public java.lang.Integer getIsDeleted() {
		return getInt("is_deleted");
	}
	
	/**
	 * 删除时间
	 */
	public void setDeletedTime(java.util.Date deletedTime) {
		set("deleted_time", deletedTime);
	}
	
	/**
	 * 删除时间
	 */
	public java.util.Date getDeletedTime() {
		return getDate("deleted_time");
	}
	
}

