package com.shopoperate.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseInvoices<M extends BaseInvoices<M>> extends Model<M> implements IBean {

	public void setId(java.math.BigInteger id) {
		set("id", id);
	}
	
	public java.math.BigInteger getId() {
		return getBigInteger("id");
	}
	
	public void setShopId(java.math.BigInteger shopId) {
		set("shop_id", shopId);
	}
	
	public java.math.BigInteger getShopId() {
		return getBigInteger("shop_id");
	}
	
	public void setReferenceType(java.lang.String referenceType) {
		set("reference_type", referenceType);
	}
	
	public java.lang.String getReferenceType() {
		return getStr("reference_type");
	}
	
	public void setReferenceId(java.math.BigInteger referenceId) {
		set("reference_id", referenceId);
	}
	
	public java.math.BigInteger getReferenceId() {
		return getBigInteger("reference_id");
	}
	
	public void setInvoiceNumber(java.lang.String invoiceNumber) {
		set("invoice_number", invoiceNumber);
	}
	
	public java.lang.String getInvoiceNumber() {
		return getStr("invoice_number");
	}
	
	public void setAmount(java.math.BigDecimal amount) {
		set("amount", amount);
	}
	
	public java.math.BigDecimal getAmount() {
		return getBigDecimal("amount");
	}
	
	public void setIssuedAt(java.util.Date issuedAt) {
		set("issued_at", issuedAt);
	}
	
	public java.util.Date getIssuedAt() {
		return getDate("issued_at");
	}
	
	public void setCreatedAt(java.util.Date createdAt) {
		set("created_at", createdAt);
	}
	
	public java.util.Date getCreatedAt() {
		return getDate("created_at");
	}
	
	/**
	 * 0-正常，1-已删除
	 */
	public void setIsDeleted(java.lang.Integer isDeleted) {
		set("is_deleted", isDeleted);
	}
	
	/**
	 * 0-正常，1-已删除
	 */
	public java.lang.Integer getIsDeleted() {
		return getInt("is_deleted");
	}
	
	/**
	 * 删除时间
	 */
	public void setDeletedTime(java.util.Date deletedTime) {
		set("deleted_time", deletedTime);
	}
	
	/**
	 * 删除时间
	 */
	public java.util.Date getDeletedTime() {
		return getDate("deleted_time");
	}
	
	/**
	 * 发票图片路径
	 */
	public void setImagePath(java.lang.String imagePath) {
		set("image_path", imagePath);
	}
	
	/**
	 * 发票图片路径
	 */
	public java.lang.String getImagePath() {
		return getStr("image_path");
	}
	
	/**
	 * 关联记录备注
	 */
	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	/**
	 * 关联记录备注
	 */
	public java.lang.String getRemark() {
		return getStr("remark");
	}
	
}

