package com.shopoperate.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseInventoryTransactions<M extends BaseInventoryTransactions<M>> extends Model<M> implements IBean {

	public void setId(java.math.BigInteger id) {
		set("id", id);
	}
	
	public java.math.BigInteger getId() {
		return getBigInteger("id");
	}
	
	public void setShopId(java.math.BigInteger shopId) {
		set("shop_id", shopId);
	}
	
	public java.math.BigInteger getShopId() {
		return getBigInteger("shop_id");
	}
	
	public void setMaterialId(java.math.BigInteger materialId) {
		set("material_id", materialId);
	}
	
	public java.math.BigInteger getMaterialId() {
		return getBigInteger("material_id");
	}
	
	/**
	 * 流水类型: 1-入库, 2-出库
	 */
	public void setTransactionType(java.lang.Integer transactionType) {
		set("transaction_type", transactionType);
	}
	
	/**
	 * 流水类型: 1-入库, 2-出库
	 */
	public java.lang.Integer getTransactionType() {
		return getInt("transaction_type");
	}
	
	public void setQuantity(java.math.BigDecimal quantity) {
		set("quantity", quantity);
	}
	
	public java.math.BigDecimal getQuantity() {
		return getBigDecimal("quantity");
	}
	
	public void setBalanceAfter(java.math.BigDecimal balanceAfter) {
		set("balance_after", balanceAfter);
	}
	
	public java.math.BigDecimal getBalanceAfter() {
		return getBigDecimal("balance_after");
	}
	
	public void setReferenceType(java.lang.String referenceType) {
		set("reference_type", referenceType);
	}
	
	public java.lang.String getReferenceType() {
		return getStr("reference_type");
	}
	
	public void setReferenceId(java.math.BigInteger referenceId) {
		set("reference_id", referenceId);
	}
	
	public java.math.BigInteger getReferenceId() {
		return getBigInteger("reference_id");
	}
	
	public void setOperatorStaffId(java.math.BigInteger operatorStaffId) {
		set("operator_staff_id", operatorStaffId);
	}
	
	public java.math.BigInteger getOperatorStaffId() {
		return getBigInteger("operator_staff_id");
	}
	
	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}
	
	public void setCreatedAt(java.util.Date createdAt) {
		set("created_at", createdAt);
	}
	
	public java.util.Date getCreatedAt() {
		return getDate("created_at");
	}
	
	/**
	 * 0-正常，1-已删除
	 */
	public void setIsDeleted(java.lang.Integer isDeleted) {
		set("is_deleted", isDeleted);
	}
	
	/**
	 * 0-正常，1-已删除
	 */
	public java.lang.Integer getIsDeleted() {
		return getInt("is_deleted");
	}
	
	/**
	 * 删除时间
	 */
	public void setDeletedTime(java.util.Date deletedTime) {
		set("deleted_time", deletedTime);
	}
	
	/**
	 * 删除时间
	 */
	public java.util.Date getDeletedTime() {
		return getDate("deleted_time");
	}
	
}

