package com.shopoperate.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOperationLogs<M extends BaseOperationLogs<M>> extends Model<M> implements IBean {

	public void setId(java.math.BigInteger id) {
		set("id", id);
	}
	
	public java.math.BigInteger getId() {
		return getBigInteger("id");
	}
	
	public void setShopId(java.math.BigInteger shopId) {
		set("shop_id", shopId);
	}
	
	public java.math.BigInteger getShopId() {
		return getBigInteger("shop_id");
	}
	
	/**
	 * 操作人: 1-员工, 2-顾客
	 */
	public void setOperatorType(java.lang.Integer operatorType) {
		set("operator_type", operatorType);
	}
	
	/**
	 * 操作人: 1-员工, 2-顾客
	 */
	public java.lang.Integer getOperatorType() {
		return getInt("operator_type");
	}
	
	public void setOperatorId(java.math.BigInteger operatorId) {
		set("operator_id", operatorId);
	}
	
	public java.math.BigInteger getOperatorId() {
		return getBigInteger("operator_id");
	}
	
	public void setAction(java.lang.String action) {
		set("action", action);
	}
	
	public java.lang.String getAction() {
		return getStr("action");
	}
	
	public void setTargetType(java.lang.String targetType) {
		set("target_type", targetType);
	}
	
	public java.lang.String getTargetType() {
		return getStr("target_type");
	}
	
	public void setTargetId(java.math.BigInteger targetId) {
		set("target_id", targetId);
	}
	
	public java.math.BigInteger getTargetId() {
		return getBigInteger("target_id");
	}
	
	public void setDetail(java.lang.String detail) {
		set("detail", detail);
	}
	
	public java.lang.String getDetail() {
		return getStr("detail");
	}
	
	public void setIpAddress(java.lang.String ipAddress) {
		set("ip_address", ipAddress);
	}
	
	public java.lang.String getIpAddress() {
		return getStr("ip_address");
	}
	
	public void setCreatedAt(java.util.Date createdAt) {
		set("created_at", createdAt);
	}
	
	public java.util.Date getCreatedAt() {
		return getDate("created_at");
	}
	
}

