package com.shopoperate.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCustomerWallets<M extends BaseCustomerWallets<M>> extends Model<M> implements IBean {

	public void setId(java.math.BigInteger id) {
		set("id", id);
	}
	
	public java.math.BigInteger getId() {
		return getBigInteger("id");
	}
	
	public void setShopId(java.math.BigInteger shopId) {
		set("shop_id", shopId);
	}
	
	public java.math.BigInteger getShopId() {
		return getBigInteger("shop_id");
	}
	
	public void setCustomerId(java.math.BigInteger customerId) {
		set("customer_id", customerId);
	}
	
	public java.math.BigInteger getCustomerId() {
		return getBigInteger("customer_id");
	}
	
	public void setBalance(java.math.BigDecimal balance) {
		set("balance", balance);
	}
	
	public java.math.BigDecimal getBalance() {
		return getBigDecimal("balance");
	}
	
	public void setTotalRecharged(java.math.BigDecimal totalRecharged) {
		set("total_recharged", totalRecharged);
	}
	
	public java.math.BigDecimal getTotalRecharged() {
		return getBigDecimal("total_recharged");
	}
	
	public void setTotalSpent(java.math.BigDecimal totalSpent) {
		set("total_spent", totalSpent);
	}
	
	public java.math.BigDecimal getTotalSpent() {
		return getBigDecimal("total_spent");
	}
	
	public void setUpdatedAt(java.util.Date updatedAt) {
		set("updated_at", updatedAt);
	}
	
	public java.util.Date getUpdatedAt() {
		return getDate("updated_at");
	}
	
	/**
	 * 0-正常，1-已删除
	 */
	public void setIsDeleted(java.lang.Integer isDeleted) {
		set("is_deleted", isDeleted);
	}
	
	/**
	 * 0-正常，1-已删除
	 */
	public java.lang.Integer getIsDeleted() {
		return getInt("is_deleted");
	}
	
	/**
	 * 删除时间
	 */
	public void setDeletedTime(java.util.Date deletedTime) {
		set("deleted_time", deletedTime);
	}
	
	/**
	 * 删除时间
	 */
	public java.util.Date getDeletedTime() {
		return getDate("deleted_time");
	}
	
}

