package com.shopoperate.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseNotificationLogs<M extends BaseNotificationLogs<M>> extends Model<M> implements IBean {

	public void setId(java.math.BigInteger id) {
		set("id", id);
	}
	
	public java.math.BigInteger getId() {
		return getBigInteger("id");
	}
	
	public void setShopId(java.math.BigInteger shopId) {
		set("shop_id", shopId);
	}
	
	public java.math.BigInteger getShopId() {
		return getBigInteger("shop_id");
	}
	
	/**
	 * 接收人: 1-顾客, 2-员工
	 */
	public void setRecipientType(java.lang.Integer recipientType) {
		set("recipient_type", recipientType);
	}
	
	/**
	 * 接收人: 1-顾客, 2-员工
	 */
	public java.lang.Integer getRecipientType() {
		return getInt("recipient_type");
	}
	
	public void setRecipientId(java.math.BigInteger recipientId) {
		set("recipient_id", recipientId);
	}
	
	public java.math.BigInteger getRecipientId() {
		return getBigInteger("recipient_id");
	}
	
	/**
	 * 渠道: 1-微信模板消息, 2-短信, 3-站内信
	 */
	public void setChannel(java.lang.Integer channel) {
		set("channel", channel);
	}
	
	/**
	 * 渠道: 1-微信模板消息, 2-短信, 3-站内信
	 */
	public java.lang.Integer getChannel() {
		return getInt("channel");
	}
	
	public void setTitle(java.lang.String title) {
		set("title", title);
	}
	
	public java.lang.String getTitle() {
		return getStr("title");
	}
	
	public void setContent(java.lang.String content) {
		set("content", content);
	}
	
	public java.lang.String getContent() {
		return getStr("content");
	}
	
	/**
	 * 状态: 1-待发送, 2-已发送, 3-发送失败
	 */
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	/**
	 * 状态: 1-待发送, 2-已发送, 3-发送失败
	 */
	public java.lang.Integer getStatus() {
		return getInt("status");
	}
	
	public void setErrorMessage(java.lang.String errorMessage) {
		set("error_message", errorMessage);
	}
	
	public java.lang.String getErrorMessage() {
		return getStr("error_message");
	}
	
	public void setSentAt(java.util.Date sentAt) {
		set("sent_at", sentAt);
	}
	
	public java.util.Date getSentAt() {
		return getDate("sent_at");
	}
	
	public void setCreatedAt(java.util.Date createdAt) {
		set("created_at", createdAt);
	}
	
	public java.util.Date getCreatedAt() {
		return getDate("created_at");
	}
	
}

