package com.shopoperate.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCoupons<M extends BaseCoupons<M>> extends Model<M> implements IBean {

	public void setId(java.math.BigInteger id) {
		set("id", id);
	}
	
	public java.math.BigInteger getId() {
		return getBigInteger("id");
	}
	
	public void setShopId(java.math.BigInteger shopId) {
		set("shop_id", shopId);
	}
	
	public java.math.BigInteger getShopId() {
		return getBigInteger("shop_id");
	}
	
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}
	
	/**
	 * 描述
	 */
	public void setDescription(java.lang.String description) {
		set("description", description);
	}
	
	/**
	 * 描述
	 */
	public java.lang.String getDescription() {
		return getStr("description");
	}
	
	/**
	 * 优惠类型: 1-固定金额, 2-百分比, 3-兑换券
	 */
	public void setType(java.lang.Integer type) {
		set("type", type);
	}
	
	/**
	 * 优惠类型: 1-固定金额, 2-百分比, 3-兑换券
	 */
	public java.lang.Integer getType() {
		return getInt("type");
	}
	
	/**
	 * 使用场景: purchase-购买套餐, recharge-充值
	 */
	public void setUseScene(java.lang.String useScene) {
		set("use_scene", useScene);
	}
	
	/**
	 * 使用场景: purchase-购买套餐, recharge-充值
	 */
	public java.lang.String getUseScene() {
		return getStr("use_scene");
	}
	
	public void setValue(java.math.BigDecimal value) {
		set("value", value);
	}
	
	public java.math.BigDecimal getValue() {
		return getBigDecimal("value");
	}
	
	public void setMinOrderAmount(java.math.BigDecimal minOrderAmount) {
		set("min_order_amount", minOrderAmount);
	}
	
	public java.math.BigDecimal getMinOrderAmount() {
		return getBigDecimal("min_order_amount");
	}
	
	public void setTotalStock(java.lang.Long totalStock) {
		set("total_stock", totalStock);
	}
	
	public java.lang.Long getTotalStock() {
		return getLong("total_stock");
	}
	
	/**
	 * 每顾客最多领取张数,0=不限
	 */
	public void setPerUserLimit(java.lang.Long perUserLimit) {
		set("per_user_limit", perUserLimit);
	}
	
	/**
	 * 每顾客最多领取张数,0=不限
	 */
	public java.lang.Long getPerUserLimit() {
		return getLong("per_user_limit");
	}
	
	public void setRemainStock(java.lang.Long remainStock) {
		set("remain_stock", remainStock);
	}
	
	public java.lang.Long getRemainStock() {
		return getLong("remain_stock");
	}
	
	public void setValidDays(java.lang.Long validDays) {
		set("valid_days", validDays);
	}
	
	public java.lang.Long getValidDays() {
		return getLong("valid_days");
	}
	
	public void setIsActive(java.lang.Integer isActive) {
		set("is_active", isActive);
	}
	
	public java.lang.Integer getIsActive() {
		return getInt("is_active");
	}
	
	/**
	 * 顾客绑手机后自动发放: 0-否, 1-是
	 */
	public void setAutoGrantOnRegister(java.lang.Integer autoGrantOnRegister) {
		set("auto_grant_on_register", autoGrantOnRegister);
	}
	
	/**
	 * 顾客绑手机后自动发放: 0-否, 1-是
	 */
	public java.lang.Integer getAutoGrantOnRegister() {
		return getInt("auto_grant_on_register");
	}
	
	public void setCreatedAt(java.util.Date createdAt) {
		set("created_at", createdAt);
	}
	
	public java.util.Date getCreatedAt() {
		return getDate("created_at");
	}
	
	public void setUpdatedAt(java.util.Date updatedAt) {
		set("updated_at", updatedAt);
	}
	
	public java.util.Date getUpdatedAt() {
		return getDate("updated_at");
	}
	
	/**
	 * 0-正常，1-已删除
	 */
	public void setIsDeleted(java.lang.Integer isDeleted) {
		set("is_deleted", isDeleted);
	}
	
	/**
	 * 0-正常，1-已删除
	 */
	public java.lang.Integer getIsDeleted() {
		return getInt("is_deleted");
	}
	
	/**
	 * 删除时间
	 */
	public void setDeletedTime(java.util.Date deletedTime) {
		set("deleted_time", deletedTime);
	}
	
	/**
	 * 删除时间
	 */
	public java.util.Date getDeletedTime() {
		return getDate("deleted_time");
	}
	
}

