package com.shopoperate.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCouponUsages<M extends BaseCouponUsages<M>> extends Model<M> implements IBean {

	public void setId(java.math.BigInteger id) {
		set("id", id);
	}
	
	public java.math.BigInteger getId() {
		return getBigInteger("id");
	}
	
	public void setShopId(java.math.BigInteger shopId) {
		set("shop_id", shopId);
	}
	
	public java.math.BigInteger getShopId() {
		return getBigInteger("shop_id");
	}
	
	public void setCouponId(java.math.BigInteger couponId) {
		set("coupon_id", couponId);
	}
	
	public java.math.BigInteger getCouponId() {
		return getBigInteger("coupon_id");
	}
	
	public void setCustomerId(java.math.BigInteger customerId) {
		set("customer_id", customerId);
	}
	
	public java.math.BigInteger getCustomerId() {
		return getBigInteger("customer_id");
	}
	
	/**
	 * 状态: 1-未使用, 2-已使用, 3-已过期
	 */
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	/**
	 * 状态: 1-未使用, 2-已使用, 3-已过期
	 */
	public java.lang.Integer getStatus() {
		return getInt("status");
	}
	
	public void setReceivedAt(java.util.Date receivedAt) {
		set("received_at", receivedAt);
	}
	
	public java.util.Date getReceivedAt() {
		return getDate("received_at");
	}
	
	public void setUsedAt(java.util.Date usedAt) {
		set("used_at", usedAt);
	}
	
	public java.util.Date getUsedAt() {
		return getDate("used_at");
	}
	
	public void setUsedInPurchaseId(java.math.BigInteger usedInPurchaseId) {
		set("used_in_purchase_id", usedInPurchaseId);
	}
	
	public java.math.BigInteger getUsedInPurchaseId() {
		return getBigInteger("used_in_purchase_id");
	}
	
	public void setExpiresAt(java.util.Date expiresAt) {
		set("expires_at", expiresAt);
	}
	
	public java.util.Date getExpiresAt() {
		return getDate("expires_at");
	}
	
	/**
	 * 0-正常，1-已删除
	 */
	public void setIsDeleted(java.lang.Integer isDeleted) {
		set("is_deleted", isDeleted);
	}
	
	/**
	 * 0-正常，1-已删除
	 */
	public java.lang.Integer getIsDeleted() {
		return getInt("is_deleted");
	}
	
	/**
	 * 删除时间
	 */
	public void setDeletedTime(java.util.Date deletedTime) {
		set("deleted_time", deletedTime);
	}
	
	/**
	 * 删除时间
	 */
	public java.util.Date getDeletedTime() {
		return getDate("deleted_time");
	}
	
}

