package com.shopoperate.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysDicts<M extends BaseSysDicts<M>> extends Model<M> implements IBean {

	public void setId(java.math.BigInteger id) {
		set("id", id);
	}
	
	public java.math.BigInteger getId() {
		return getBigInteger("id");
	}
	
	/**
	 * 字典分组编码（如：order_status, package_type）
	 */
	public void setDictCode(java.lang.String dictCode) {
		set("dict_code", dictCode);
	}
	
	/**
	 * 字典分组编码（如：order_status, package_type）
	 */
	public java.lang.String getDictCode() {
		return getStr("dict_code");
	}
	
	/**
	 * 业务表实际存储的整数值
	 */
	public void setDictKey(java.lang.Integer dictKey) {
		set("dict_key", dictKey);
	}
	
	/**
	 * 业务表实际存储的整数值
	 */
	public java.lang.Integer getDictKey() {
		return getInt("dict_key");
	}
	
	/**
	 * 前端展示值（如：有效、已退款）
	 */
	public void setDictValue(java.lang.String dictValue) {
		set("dict_value", dictValue);
	}
	
	/**
	 * 前端展示值（如：有效、已退款）
	 */
	public java.lang.String getDictValue() {
		return getStr("dict_value");
	}
	
	/**
	 * 代码常量标识（如：VALID, REFUNDED）
	 */
	public void setDictLabel(java.lang.String dictLabel) {
		set("dict_label", dictLabel);
	}
	
	/**
	 * 代码常量标识（如：VALID, REFUNDED）
	 */
	public java.lang.String getDictLabel() {
		return getStr("dict_label");
	}
	
	/**
	 * 排序
	 */
	public void setSort(java.lang.Long sort) {
		set("sort", sort);
	}
	
	/**
	 * 排序
	 */
	public java.lang.Long getSort() {
		return getLong("sort");
	}
	
	/**
	 * 1-启用，0-禁用
	 */
	public void setIsActive(java.lang.Integer isActive) {
		set("is_active", isActive);
	}
	
	/**
	 * 1-启用，0-禁用
	 */
	public java.lang.Integer getIsActive() {
		return getInt("is_active");
	}
	
	/**
	 * 0=全局默认，>0=租户自定义覆盖
	 */
	public void setShopId(java.math.BigInteger shopId) {
		set("shop_id", shopId);
	}
	
	/**
	 * 0=全局默认，>0=租户自定义覆盖
	 */
	public java.math.BigInteger getShopId() {
		return getBigInteger("shop_id");
	}
	
	public void setCreatedAt(java.util.Date createdAt) {
		set("created_at", createdAt);
	}
	
	public java.util.Date getCreatedAt() {
		return getDate("created_at");
	}
	
	public void setUpdatedAt(java.util.Date updatedAt) {
		set("updated_at", updatedAt);
	}
	
	public java.util.Date getUpdatedAt() {
		return getDate("updated_at");
	}
	
}

