package com.shopoperate.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMaterials<M extends BaseMaterials<M>> extends Model<M> implements IBean {

	public void setId(java.math.BigInteger id) {
		set("id", id);
	}
	
	public java.math.BigInteger getId() {
		return getBigInteger("id");
	}
	
	public void setShopId(java.math.BigInteger shopId) {
		set("shop_id", shopId);
	}
	
	public java.math.BigInteger getShopId() {
		return getBigInteger("shop_id");
	}
	
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}
	
	public void setSku(java.lang.String sku) {
		set("sku", sku);
	}
	
	public java.lang.String getSku() {
		return getStr("sku");
	}
	
	/**
	 * 店铺自定义物料分类
	 */
	public void setCategory(java.lang.String category) {
		set("category", category);
	}
	
	/**
	 * 店铺自定义物料分类
	 */
	public java.lang.String getCategory() {
		return getStr("category");
	}
	
	/**
	 * 单位
	 */
	public void setUnit(java.lang.String unit) {
		set("unit", unit);
	}
	
	/**
	 * 单位
	 */
	public java.lang.String getUnit() {
		return getStr("unit");
	}
	
	/**
	 * 物料类型: 1-消耗品, 2-工具
	 */
	public void setType(java.lang.Integer type) {
		set("type", type);
	}
	
	/**
	 * 物料类型: 1-消耗品, 2-工具
	 */
	public java.lang.Integer getType() {
		return getInt("type");
	}
	
	public void setMinStock(java.math.BigDecimal minStock) {
		set("min_stock", minStock);
	}
	
	public java.math.BigDecimal getMinStock() {
		return getBigDecimal("min_stock");
	}
	
	public void setImageUrl(java.lang.String imageUrl) {
		set("image_url", imageUrl);
	}
	
	public java.lang.String getImageUrl() {
		return getStr("image_url");
	}
	
	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}
	
	public void setIsDeleted(java.lang.Integer isDeleted) {
		set("is_deleted", isDeleted);
	}
	
	public java.lang.Integer getIsDeleted() {
		return getInt("is_deleted");
	}
	
	public void setCreatedAt(java.util.Date createdAt) {
		set("created_at", createdAt);
	}
	
	public java.util.Date getCreatedAt() {
		return getDate("created_at");
	}
	
	public void setUpdatedAt(java.util.Date updatedAt) {
		set("updated_at", updatedAt);
	}
	
	public java.util.Date getUpdatedAt() {
		return getDate("updated_at");
	}
	
	/**
	 * 删除时间
	 */
	public void setDeletedTime(java.util.Date deletedTime) {
		set("deleted_time", deletedTime);
	}
	
	/**
	 * 删除时间
	 */
	public java.util.Date getDeletedTime() {
		return getDate("deleted_time");
	}
	
}

