package com.shopoperate.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRolePermissions<M extends BaseRolePermissions<M>> extends Model<M> implements IBean {

	public void setRoleId(java.math.BigInteger roleId) {
		set("role_id", roleId);
	}
	
	public java.math.BigInteger getRoleId() {
		return getBigInteger("role_id");
	}
	
	public void setPermissionId(java.math.BigInteger permissionId) {
		set("permission_id", permissionId);
	}
	
	public java.math.BigInteger getPermissionId() {
		return getBigInteger("permission_id");
	}
	
}

