package com.shopoperate.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFeedbacks<M extends BaseFeedbacks<M>> extends Model<M> implements IBean {

	public void setId(java.math.BigInteger id) {
		set("id", id);
	}
	
	public java.math.BigInteger getId() {
		return getBigInteger("id");
	}
	
	/**
	 * 店铺ID
	 */
	public void setShopId(java.math.BigInteger shopId) {
		set("shop_id", shopId);
	}
	
	/**
	 * 店铺ID
	 */
	public java.math.BigInteger getShopId() {
		return getBigInteger("shop_id");
	}
	
	/**
	 * 顾客ID
	 */
	public void setCustomerId(java.math.BigInteger customerId) {
		set("customer_id", customerId);
	}
	
	/**
	 * 顾客ID
	 */
	public java.math.BigInteger getCustomerId() {
		return getBigInteger("customer_id");
	}
	
	/**
	 * 关联的游玩记录ID
	 */
	public void setGameSessionId(java.math.BigInteger gameSessionId) {
		set("game_session_id", gameSessionId);
	}
	
	/**
	 * 关联的游玩记录ID
	 */
	public java.math.BigInteger getGameSessionId() {
		return getBigInteger("game_session_id");
	}
	
	/**
	 * 反馈类型: 1-满意度 2-建议 3-投诉 4-其他
	 */
	public void setFeedbackType(java.lang.Integer feedbackType) {
		set("feedback_type", feedbackType);
	}
	
	/**
	 * 反馈类型: 1-满意度 2-建议 3-投诉 4-其他
	 */
	public java.lang.Integer getFeedbackType() {
		return getInt("feedback_type");
	}
	
	/**
	 * 评分: 1-5星
	 */
	public void setRating(java.lang.Integer rating) {
		set("rating", rating);
	}
	
	/**
	 * 评分: 1-5星
	 */
	public java.lang.Integer getRating() {
		return getInt("rating");
	}
	
	/**
	 * 反馈内容
	 */
	public void setContent(java.lang.String content) {
		set("content", content);
	}
	
	/**
	 * 反馈内容
	 */
	public java.lang.String getContent() {
		return getStr("content");
	}
	
	/**
	 * 图片URL数组
	 */
	public void setImages(java.lang.String images) {
		set("images", images);
	}
	
	/**
	 * 图片URL数组
	 */
	public java.lang.String getImages() {
		return getStr("images");
	}
	
	/**
	 * 状态: 1-待处理 2-已回复 3-已关闭
	 */
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	/**
	 * 状态: 1-待处理 2-已回复 3-已关闭
	 */
	public java.lang.Integer getStatus() {
		return getInt("status");
	}
	
	/**
	 * 管理员回复内容
	 */
	public void setReplyContent(java.lang.String replyContent) {
		set("reply_content", replyContent);
	}
	
	/**
	 * 管理员回复内容
	 */
	public java.lang.String getReplyContent() {
		return getStr("reply_content");
	}
	
	/**
	 * 回复人ID（staff表）
	 */
	public void setRepliedBy(java.math.BigInteger repliedBy) {
		set("replied_by", repliedBy);
	}
	
	/**
	 * 回复人ID（staff表）
	 */
	public java.math.BigInteger getRepliedBy() {
		return getBigInteger("replied_by");
	}
	
	/**
	 * 回复时间
	 */
	public void setRepliedAt(java.util.Date repliedAt) {
		set("replied_at", repliedAt);
	}
	
	/**
	 * 回复时间
	 */
	public java.util.Date getRepliedAt() {
		return getDate("replied_at");
	}
	
	public void setCreatedAt(java.util.Date createdAt) {
		set("created_at", createdAt);
	}
	
	public java.util.Date getCreatedAt() {
		return getDate("created_at");
	}
	
	public void setUpdatedAt(java.util.Date updatedAt) {
		set("updated_at", updatedAt);
	}
	
	public java.util.Date getUpdatedAt() {
		return getDate("updated_at");
	}
	
	/**
	 * 0-正常，1-已删除
	 */
	public void setIsDeleted(java.lang.Integer isDeleted) {
		set("is_deleted", isDeleted);
	}
	
	/**
	 * 0-正常，1-已删除
	 */
	public java.lang.Integer getIsDeleted() {
		return getInt("is_deleted");
	}
	
	/**
	 * 删除时间
	 */
	public void setDeletedTime(java.util.Date deletedTime) {
		set("deleted_time", deletedTime);
	}
	
	/**
	 * 删除时间
	 */
	public java.util.Date getDeletedTime() {
		return getDate("deleted_time");
	}
	
}

