package com.shopoperate.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRefundRecords<M extends BaseRefundRecords<M>> extends Model<M> implements IBean {

	public void setId(java.math.BigInteger id) {
		set("id", id);
	}
	
	public java.math.BigInteger getId() {
		return getBigInteger("id");
	}
	
	public void setShopId(java.math.BigInteger shopId) {
		set("shop_id", shopId);
	}
	
	public java.math.BigInteger getShopId() {
		return getBigInteger("shop_id");
	}
	
	public void setPurchaseId(java.math.BigInteger purchaseId) {
		set("purchase_id", purchaseId);
	}
	
	public java.math.BigInteger getPurchaseId() {
		return getBigInteger("purchase_id");
	}
	
	public void setRefundAmount(java.math.BigDecimal refundAmount) {
		set("refund_amount", refundAmount);
	}
	
	public java.math.BigDecimal getRefundAmount() {
		return getBigDecimal("refund_amount");
	}
	
	public void setReason(java.lang.String reason) {
		set("reason", reason);
	}
	
	public java.lang.String getReason() {
		return getStr("reason");
	}
	
	public void setDeductedAmount(java.math.BigDecimal deductedAmount) {
		set("deducted_amount", deductedAmount);
	}
	
	public java.math.BigDecimal getDeductedAmount() {
		return getBigDecimal("deducted_amount");
	}
	
	public void setRefundPrepayAmount(java.math.BigDecimal refundPrepayAmount) {
		set("refund_prepay_amount", refundPrepayAmount);
	}
	
	public java.math.BigDecimal getRefundPrepayAmount() {
		return getBigDecimal("refund_prepay_amount");
	}
	
	public void setRefundWalletAmount(java.math.BigDecimal refundWalletAmount) {
		set("refund_wallet_amount", refundWalletAmount);
	}
	
	public java.math.BigDecimal getRefundWalletAmount() {
		return getBigDecimal("refund_wallet_amount");
	}
	
	public void setRefundedSessions(java.lang.Long refundedSessions) {
		set("refunded_sessions", refundedSessions);
	}
	
	public java.lang.Long getRefundedSessions() {
		return getLong("refunded_sessions");
	}
	
	/**
	 * 状态: 1-处理中, 2-已完成, 3-已拒绝
	 */
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	/**
	 * 状态: 1-处理中, 2-已完成, 3-已拒绝
	 */
	public java.lang.Integer getStatus() {
		return getInt("status");
	}
	
	public void setOperatedBy(java.math.BigInteger operatedBy) {
		set("operated_by", operatedBy);
	}
	
	public java.math.BigInteger getOperatedBy() {
		return getBigInteger("operated_by");
	}
	
	public void setCreatedAt(java.util.Date createdAt) {
		set("created_at", createdAt);
	}
	
	public java.util.Date getCreatedAt() {
		return getDate("created_at");
	}
	
	public void setUpdatedAt(java.util.Date updatedAt) {
		set("updated_at", updatedAt);
	}
	
	public java.util.Date getUpdatedAt() {
		return getDate("updated_at");
	}
	
	/**
	 * 0-正常，1-已删除
	 */
	public void setIsDeleted(java.lang.Integer isDeleted) {
		set("is_deleted", isDeleted);
	}
	
	/**
	 * 0-正常，1-已删除
	 */
	public java.lang.Integer getIsDeleted() {
		return getInt("is_deleted");
	}
	
	/**
	 * 删除时间
	 */
	public void setDeletedTime(java.util.Date deletedTime) {
		set("deleted_time", deletedTime);
	}
	
	/**
	 * 删除时间
	 */
	public java.util.Date getDeletedTime() {
		return getDate("deleted_time");
	}
	
	/**
	 * 关联反向收入记录ID
	 */
	public void setRevenueId(java.lang.Long revenueId) {
		set("revenue_id", revenueId);
	}
	
	/**
	 * 关联反向收入记录ID
	 */
	public java.lang.Long getRevenueId() {
		return getLong("revenue_id");
	}
	
}

