package com.shopoperate.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePointsRecords<M extends BasePointsRecords<M>> extends Model<M> implements IBean {

	public void setId(java.math.BigInteger id) {
		set("id", id);
	}
	
	public java.math.BigInteger getId() {
		return getBigInteger("id");
	}
	
	public void setShopId(java.math.BigInteger shopId) {
		set("shop_id", shopId);
	}
	
	public java.math.BigInteger getShopId() {
		return getBigInteger("shop_id");
	}
	
	public void setCustomerId(java.math.BigInteger customerId) {
		set("customer_id", customerId);
	}
	
	public java.math.BigInteger getCustomerId() {
		return getBigInteger("customer_id");
	}
	
	/**
	 * 类型: 1-获取, 2-消耗, 3-过期, 4-调整
	 */
	public void setType(java.lang.Integer type) {
		set("type", type);
	}
	
	/**
	 * 类型: 1-获取, 2-消耗, 3-过期, 4-调整
	 */
	public java.lang.Integer getType() {
		return getInt("type");
	}
	
	public void setPoints(java.lang.Integer points) {
		set("points", points);
	}
	
	public java.lang.Integer getPoints() {
		return getInt("points");
	}
	
	public void setBalanceAfter(java.lang.Integer balanceAfter) {
		set("balance_after", balanceAfter);
	}
	
	public java.lang.Integer getBalanceAfter() {
		return getInt("balance_after");
	}
	
	public void setSource(java.lang.String source) {
		set("source", source);
	}
	
	public java.lang.String getSource() {
		return getStr("source");
	}
	
	public void setReferenceId(java.math.BigInteger referenceId) {
		set("reference_id", referenceId);
	}
	
	public java.math.BigInteger getReferenceId() {
		return getBigInteger("reference_id");
	}
	
	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}
	
	public void setCreatedAt(java.util.Date createdAt) {
		set("created_at", createdAt);
	}
	
	public java.util.Date getCreatedAt() {
		return getDate("created_at");
	}
	
	/**
	 * 0-正常，1-已删除
	 */
	public void setIsDeleted(java.lang.Integer isDeleted) {
		set("is_deleted", isDeleted);
	}
	
	/**
	 * 0-正常，1-已删除
	 */
	public java.lang.Integer getIsDeleted() {
		return getInt("is_deleted");
	}
	
	/**
	 * 删除时间
	 */
	public void setDeletedTime(java.util.Date deletedTime) {
		set("deleted_time", deletedTime);
	}
	
	/**
	 * 删除时间
	 */
	public java.util.Date getDeletedTime() {
		return getDate("deleted_time");
	}
	
}

